feat(optimus): [RND-65933] Add standalone link
MewsSystems/mews-flutter pull request #105
Opened 2021-07-15 06:51 UTC by Gladkowski

#### Summary

- add standalone link
- `inherit` and `external` properties are not implemented

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-07-15 08:13 UTC, chaeMil requested changes

2021-07-15 08:13 UTC, chaeMil commented on optimus/lib/src/standalone_link.dart
> +                children: [
Why is this here? It looks and function without it.

2021-07-15 10:20 UTC, chaeMil approved these changes

2021-07-16 14:51 UTC, ookami-kb commented on optimus/lib/src/standalone_link.dart
> +  final bool isInherit;
When using like this, it's even more confusing than before. How should user understand that `isInherit` makes the link color black?

Can we somehow make it aligned with optimus guidelines and create a more meaningful parameter name?

2021-07-16 15:29 UTC, Gladkowski commented on optimus/lib/src/standalone_link.dart
> +  final bool isInherit;
What about `isDefault`?

2021-07-19 10:06 UTC, ookami-kb commented on optimus/lib/src/standalone_link.dart
> +            onTap: widget.onPressed,
Why is `onTap` used both here and in `_gestureRecognizer`?

2021-07-19 10:29 UTC, ookami-kb commented on optimus/lib/src/standalone_link.dart
> +            child: Text.rich(
Actually, I think we don't need rich text at all for a standalone link.

2021-07-19 10:34 UTC, Gladkowski commented on optimus/lib/src/standalone_link.dart
> +            child: Text.rich(
well, valid idea

2021-07-19 10:39 UTC, ookami-kb approved these changes

2021-07-19 10:39 UTC, merged