:zap: [RND-48076] Add dropdown button
MewsSystems/mews-flutter pull request #11
Opened 2021-02-10 14:33 UTC by Gladkowski

- Minimum dropdown size is 300 px (verified by designers).

2021-02-10 17:48 UTC, chaeMil commented on optimus/lib/src/dropdown_button.dart
> +  Color get _highLightColor {
Just a small thing, I would rename it to `_highlightColor` just lower the L

2021-02-10 17:50 UTC, chaeMil requested changes

2021-02-10 17:50 UTC, chaeMil commented on optimus/lib/src/dropdown_button.dart
> +                  padding: const EdgeInsets.symmetric(horizontal: 16),
Please use `spacing200` here

2021-02-11 08:23 UTC, chaeMil approved these changes

2021-02-12 10:32 UTC, ookami-kb requested changes

2021-02-12 10:32 UTC, ookami-kb commented on optimus/lib/src/search/search_field_dropdown.dart
> +    final isLeftToRight = _rightSpace >= widget.width + _widgetPadding;
Select is broken now.

2021-02-16 17:41 UTC, ookami-kb commented
@Gladkowski @chaeMil I've pushed some updates. I hope I didn't break positioning, please check it.

2021-02-17 08:02 UTC, Gladkowski commented
> @Gladkowski @chaeMil I've pushed some updates. I hope I didn't break positioning, please check it.

@ookami-kb @chaeMil _Right to Left_ dropdown position was broken. I've added little fix. Please check.

2021-02-17 10:49 UTC, chaeMil commented
@ookami-kb @Gladkowski checked :)

2021-02-17 11:31 UTC, ookami-kb approved these changes

2021-02-17 11:32 UTC, merged