Add toggling of avatar widget
MewsSystems/mews-flutter pull request #125
Opened 2021-08-16 13:26 UTC by chaeMil

#### Summary

Added boolean to toggle the avatar widget. Its used not for hiding but for enabling the avatar support.

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-08-16 13:40 UTC, Gladkowski requested changes

2021-08-16 13:40 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +      : Container();
I would revert this change to 
```
Widget get _avatar => SizedBox(
        width: 40,
        child: isAvatarVisible ? message.avatar : null,
      );
```

And add the check to `line:240` and `line:242` like:
`if (message.alignment == MessageAlignment.left && isAvatarVisible) _avatar,`

2021-08-16 13:45 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +      : Container();
Yep looks better :)

2021-08-16 13:58 UTC, Gladkowski approved these changes

2021-08-17 08:49 UTC, ookami-kb requested changes

2021-08-17 08:49 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final bool isAvatarEnabled;
Maybe something like `hasAvatars` would be better?

2021-08-17 08:49 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +                isAvatarEnabled: isAvatarEnabled,
This looks messy with chat bubble controlling padding based on avatar.

Let's rather make the chat component control avatar rendering and padding, and bubble will render the rest.

2021-08-19 09:05 UTC, ookami-kb requested changes

2021-08-19 09:05 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  Widget _avatar(int index) => Padding(
`_buildAvatar`

2021-08-19 09:05 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +                  if (_messages[index].alignment == MessageAlignment.left &&
Nitpicking: `hasAvatars && ...` would be slightly more readable – `hasAvatars` sounds more important, if there's no avatar, other checks don't make sense.

2021-08-19 09:17 UTC, ookami-kb approved these changes

2021-08-19 09:17 UTC, merged