feat: Add loader
MewsSystems/mews-flutter pull request #126
Opened 2021-08-17 06:39 UTC by Gladkowski

#### Summary

Add [circle loader](https://mews.design/7b4bb574e/p/93f3c4-circle-loader/b/32e1a2).

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-08-17 08:35 UTC, chaeMil requested changes
just a nitpicking, otherwise looking good

2021-08-17 08:35 UTC, chaeMil commented on optimus/lib/src/loader/painter.dart
> +    final double strokeWidth = size.width / 10;
nitpicking: works even without the type

2021-08-17 09:59 UTC, chaeMil approved these changes

2021-08-23 09:39 UTC, ookami-kb requested changes

2021-08-23 09:39 UTC, ookami-kb commented on optimus/lib/src/loader/loader.dart
> +  })  : assert(
Instead of complex asserts use ADT: loader should be **either** indeterminate **or** determinate with non-nullable progress, which is a direct candidate for a freezed union type.

2021-08-24 10:46 UTC, ookami-kb requested changes

2021-08-24 10:46 UTC, ookami-kb commented on optimus/lib/src/loader/painter.dart
> +    /// Track circle
What's the point of this comment (and the one on line 35)? They are basically repeating the variable name.

2021-08-24 10:46 UTC, ookami-kb commented on optimus/lib/src/loader/loader.dart
> +  /// Progress should either be null or in [0, 100] range.
Progress cannot be null.

2021-08-24 10:46 UTC, ookami-kb commented on optimus/lib/src/loader/loader.dart
> +  /// The inverted option uses the neural white color, and it is designed to be
neutral

2021-08-24 11:16 UTC, ookami-kb commented on optimus/lib/src/loader/loader.dart
> +  /// Progress should either be null or in [0, 100] range.
Comment is not updated.

2021-08-24 11:16 UTC, ookami-kb commented on optimus/lib/src/loader/loader.dart
> +  /// The contrast option uses the neural white color, and it is designed to be
`neutral` word is not fixed

2021-08-24 11:30 UTC, ookami-kb approved these changes

2021-08-24 11:32 UTC, merged