Add bottom padding to chat bubble
MewsSystems/mews-flutter pull request #128
Opened 2021-08-24 11:38 UTC by chaeMil

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-08-24 11:49 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +        padding: EdgeInsets.only(bottom: _showAvatar(index) ? 34 : 0),
Where does this `34` come from?

2021-08-24 12:06 UTC, chaeMil commented on optimus/lib/src/chat/chat.dart
> +        padding: EdgeInsets.only(bottom: _showAvatar(index) ? 34 : 0),
16 from the status padding and then plus its current 18. I know its a magic number :/

2021-08-24 12:35 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +        padding: EdgeInsets.only(bottom: _showAvatar(index) ? 34 : 0),
I think the layout should rather be updated. Basically, avatar is bottom-aligned with the message, so it can be something like this:

```
-------- -------------
Avatar   | Message            <- row
-------- -------------
              | Timestamp
```

I guess, currently `18` is coming from the timestamp height, so it will be broken if use has non-default font size.

2021-08-24 12:39 UTC, chaeMil commented on optimus/lib/src/chat/chat.dart
> +        padding: EdgeInsets.only(bottom: _showAvatar(index) ? 34 : 0),
So the only option to do this is move the status text to chat widget outside of the bubble.

2021-08-25 09:43 UTC, Sevastyan requested changes
No PR description - no review.

2021-08-29 09:39 UTC, Sevastyan approved these changes

2021-08-30 10:20 UTC, ookami-kb requested changes

2021-08-30 10:20 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final bool Function(OptimusMessage) isFromCurrentUser;
Nitpicking: can be changed to `final Predicate<OptimusMessage> isFromCurrentUser` from `dfunc`.

2021-08-30 10:20 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +import 'package:optimus/src/chat/optimus_chat_input.dart';
No padding: 
<img width="658" alt="Screenshot 2021-08-30 at 12 04 40" src="https://user-images.githubusercontent.com/853356/131323240-96baa431-6236-4da5-9012-6ebf9027ecfa.png">

2021-08-30 11:08 UTC, ookami-kb approved these changes
Currently, the chat interface looks inconsistent to me (in terms of parameters, avatars/username displaying etc). Merging it for now to update in the app, but we'll need to refactor it later.

2021-08-30 11:09 UTC, merged

2021-08-30 11:32 UTC, chaeMil commented
> Currently, the chat interface looks inconsistent to me (in terms of parameters, avatars/username displaying etc). Merging it for now to update in the app, but we'll need to refactor it later.

I will create task for this