feat(optimus): Add clear button to input and date time field
MewsSystems/mews-flutter pull request #135
Opened 2021-09-02 13:11 UTC by Gladkowski

#### Summary

Add clear button to `input filed` and `date time` field.

- [input filed design ](https://mews.design/7b4bb574e/p/5037e4-text-input/b/32e1a2) 
- date time field is a mobile specific component, and probably we should move it to commander client

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-09-02 14:17 UTC, chaeMil requested changes

2021-09-02 14:17 UTC, chaeMil commented on storybook/pubspec.yaml
> +  intl: ^0.17.0
Why introducing this library? And dragging this to the end user.

2021-09-02 14:17 UTC, chaeMil commented on storybook/lib/stories/date_time_field.dart
> +          formatDateTime: DateFormat().format,
This is not necessary, just provide a function.

2021-09-02 17:50 UTC, chaeMil approved these changes

2021-09-03 08:55 UTC, ookami-kb requested changes

2021-09-03 08:55 UTC, ookami-kb commented on optimus/lib/src/date_time_field.dart
> +      this.placeholder})
Add trailing comma.

2021-09-03 08:55 UTC, ookami-kb commented on optimus/lib/src/date_time_field.dart
> +  final bool isClearAllEnabled;
I would rather rename it to `isClearEnabled` everywhere, all doesn't add any value.

2021-09-03 08:55 UTC, ookami-kb commented on optimus/lib/src/input_field.dart
> +      : widget.suffix;
Can be simplified:

```suggestion
  Widget get _suffix => OptimusStack(
        direction: Axis.horizontal,
        spacing: OptimusStackSpacing.spacing100,
        mainAxisSize: MainAxisSize.min,
        children: [
          if (widget.isClearAllEnabled)
            _ClearAllButton(
              onTap: () {
                _controller?.clear();
                widget.onChanged?.call('');
              },
            ),
          if (widget.suffix != null) widget.suffix!,
        ],
      );
```

2021-09-03 12:34 UTC, ookami-kb requested changes

2021-09-03 12:34 UTC, ookami-kb commented on optimus/lib/src/input_field.dart
> +    _controller = widget.controller ?? TextEditingController();
If you're creating `TextEditingController` you should also dispose of it, it's the same as with focus nodes.

2021-09-06 13:34 UTC, Gladkowski commented
@ookami-kb ping

2021-09-06 14:27 UTC, ookami-kb commented on optimus/lib/src/input_field.dart
> +      widget.controller ?? _controller!;
Why `!`? Use the same construction as in the focus node.

2021-09-06 14:37 UTC, ookami-kb approved these changes

2021-09-06 14:39 UTC, merged