Make badge text optional
MewsSystems/mews-flutter pull request #152
Opened 2021-09-30 15:17 UTC by chaeMil

#### Summary

Make badge text optional and change rendering of badge based on that.

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

Needed for [this](https://github.com/MewsSystems/mews-mobile-commander/pull/888)

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-10-01 14:07 UTC, chaeMil commented
@Gladkowski ping

2021-10-01 14:10 UTC, Gladkowski requested changes

2021-10-01 14:10 UTC, Gladkowski commented on optimus/lib/src/badge.dart
> +  bool get hasText => text != null && text!.isNotEmpty;
I would make it private `_hasText`

2021-10-04 06:08 UTC, Gladkowski approved these changes

2021-10-04 08:06 UTC, ookami-kb requested changes

2021-10-04 08:06 UTC, ookami-kb commented on optimus/lib/src/badge.dart
> +  bool get _hasText => text != null && text!.isNotEmpty;
Since we don't distinguish between `null` and empty string, make the `text` param non-nullable with empty string by default.

2021-10-04 08:41 UTC, ookami-kb commented on optimus/lib/src/badge.dart
> +  bool get _hasText => text.isNotEmpty;
Nitpicking: let's make it a local variable inside the `build` method, it's not used anywhere outside.

2021-10-04 08:58 UTC, ookami-kb approved these changes

2021-10-04 08:58 UTC, merged