feat(optimus): Make `OptimusNumberPicker` public
MewsSystems/mews-flutter pull request #170
Opened 2021-11-16 11:35 UTC by chaeMil

#### Summary

Make `OptimusNumberPicker` public. 
Needed for [RND-84283](https://mews.myjetbrains.com/youtrack/issue/RND-84283);

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-11-16 14:14 UTC, Sevastyan commented
@chaeMil Please, don't forget to fill in testing steps and follow-up issues sections in PR description.

2021-11-16 14:45 UTC, chaeMil commented
> @chaeMil Please, don't forget to fill in testing steps and follow-up issues sections in PR description.

Done

2021-11-16 15:02 UTC, Sevastyan requested changes
Describe the intended solution for the issue RND-84283 first, please. Without it, I cannot really judge these changes.

How making `OptimusNumberPicker` public will solve the problem? It is not used anywhere (and should not be used). Adding a constructor parameter to `OptimusNumberPickerFormField` should be done instead to achieve what I think the intention is.

2021-11-16 15:02 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +  late final NumberPickerController? _numberPickerController =
Don't make a property `late` and nullable at the same time. It should be either `late`, or nullable and variable. We prefer the later one.

2021-11-16 15:02 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +  late final Function(int value) onSetValue;
Naming. Better have it as `onValueSet`.

2021-11-18 08:29 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +class NumberPickerController {
To set the value from outside the widget.

2021-11-18 10:54 UTC, Sevastyan approved these changes

2021-11-18 10:56 UTC, Sevastyan commented
@chaeMil "Controller" should do more than just setting a value, i.e. the name implies it has more methods.

2021-11-18 16:11 UTC, ookami-kb reviewed
Why not just pass optional controller instead of doing this "callback of a callback"?

2021-11-19 13:15 UTC, chaeMil commented
> Why not just pass optional controller instead of doing this "callback of a callback"?

Honestly im ok with both variants. @Sevastyan

2021-11-19 13:51 UTC, Sevastyan commented
@ookami-kb do you mean `TextEditingController`? Then, I guess in order to have a lean API. Widget should only expose the ability of setting the value, from what I got from the issue description.

2021-11-19 15:09 UTC, ookami-kb commented
This is a common practice (and in some cases a necessity, actually) to pass the controller to the form field. Take a look at [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html), for example.

2021-11-19 15:38 UTC, Sevastyan commented
Let's refactor it then, if it's a common practice.

2021-11-22 09:44 UTC, chaeMil commented
@ookami-kb plese check

2021-11-22 11:40 UTC, ookami-kb commented
@chaeMil I was talking about passing `TextEditingController` instead of a custom controller.

2021-11-22 13:01 UTC, chaeMil commented
@ookami-kb but then there will be problem with the `_value` not being set` without some nasty widget internal work.

2021-11-22 13:03 UTC, ookami-kb commented
@chaeMil what do you mean?

2021-11-22 13:07 UTC, chaeMil commented
Take a look at lines `115` and `125`. After the press the internal `_value` is changed. But when we change the text with `_textEditingController` the `_value` will not update thus the widget will not work correctly.

2021-11-23 09:07 UTC, chaeMil commented
@ookami-kb  ready

2021-11-23 11:13 UTC, ookami-kb requested changes

2021-11-23 11:13 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    _textEditingController.dispose();
You cannot just dispose a controller that potentially comes from the widget. Only the entity that creates something is in charge of disposing it. Take a look at focus node.

Also, how does this widget react to controller value update?

2021-11-23 12:23 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +    _textEditingController.dispose();
OK but im still unsure how to deal with that :/

2021-11-23 12:25 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    _textEditingController.dispose();
In the same way as focus node is treated. If it is external controller, do nothing, if internal – dispose it.

2021-11-24 12:28 UTC, Sevastyan reviewed
Shouldn't a controllers listener trigger `_updateValue` ?

```
diff --git a/optimus/lib/src/number_picker/number_picker.dart b/optimus/lib/src/number_picker/number_picker.dart
index 97140fd..abcd9d8 100644
--- a/optimus/lib/src/number_picker/number_picker.dart
+++ b/optimus/lib/src/number_picker/number_picker.dart
@@ -125,7 +125,6 @@ class _OptimusNumberPickerState extends State<_OptimusNumberPicker> {
         : _value > widget.max
             ? widget.max
             : _value - 1;
-    _updateValue(value);
     _updateController(value);
   }
 
@@ -135,7 +134,6 @@ class _OptimusNumberPickerState extends State<_OptimusNumberPicker> {
         : _value > widget.max - 1
             ? widget.max
             : _value + 1;
-    _updateValue(value);
     _updateController(value);
   }
 
```

2021-11-25 09:32 UTC, ookami-kb requested changes

2021-11-25 09:32 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +        text: widget.initialValue?.toString() ?? '',
Initial value should be passed to controller even if it's external one.

2021-11-25 09:32 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    _effectiveController.addListener(() {
Listener should be removed from `_effectiveController` on dispose.

2021-11-25 09:32 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +      if (value != null) {
I'm not thinking, let's probably remove `defaultValue` and make all the callbacks and `_value` nullable. As it turned out, this "default value" concept is pretty confusing – we should explicitly describe the situation "there's no correct value entered". So it will be up to a caller to fallback to default value if needed.

2021-11-26 10:20 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +      if (value != null) {
Can we maybe take a look at this together? When trying to accomplish this it became a huge mess so either im not getting it right or it's just a huge mess :D

2021-11-29 14:39 UTC, chaeMil commented
ping @Sevastyan @ookami-kb

2021-11-30 10:25 UTC, Sevastyan requested changes

2021-11-30 10:25 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +            onPressed: (_value ?? widget.max) > widget.min ? _onMinusTap : null,
`?? widget.max` is logic duplication. It should be:

```dart
onPressed: _value == null || _value! > widget.min ? _onMinusTap : null,
```

to achieve the same behaviour.

2021-11-30 10:25 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +            onPressed: (_value ?? widget.min) < widget.max ? _onPlusTap : null,
```dart
onPressed: _value == null || _value! < widget.max ? _onPlusTap : null,
```

2021-11-30 10:32 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +      value = widget.max;
I added the opposite ends of the range in plus/minus buttons. It felt natural to me that if theres no value you press minus it will select the highest possible and then you can decrease it same as on the plus button side but in reverse.

2021-11-30 10:37 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +          validator: (value) => value == null || (value >= min && value <= max)
Yeah looking at it at retrospectively this doesnt make much sense :D

2021-11-30 10:49 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +  late int? _value = widget.initialValue;
We can add assert that setting `initialValue` and `controller` is not allowed.

2021-11-30 10:59 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +      value = widget.max;
I got it. It isn't what I would expect as a user though.

2021-11-30 11:03 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +  late int? _value = widget.initialValue;
We can, but we can also delete `initialValue`. Not sure what is considered more appropriate in Flutter world. @ookami-kb

2021-11-30 11:06 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +      value = widget.max;
Since this is a matter of preference, what about pushing this decision to the client?

2021-11-30 11:12 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +      value = widget.max;
Or we can use `initialValue` if we are not going to get rid of it

2021-11-30 11:24 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +  late int? _value = widget.initialValue;
Yes, what's @chaeMil suggested is reasonable, this is how it's done in `TextFormField`:

```dart
  /// When a [controller] is specified, [initialValue] must be null (the
  /// default). If [controller] is null, then a [TextEditingController]
  /// will be constructed automatically and its `text` will be initialized
  /// to [initialValue] or the empty string.
```

2021-11-30 11:26 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +      value = widget.max;
I've checked how it's done in HTML `<input type="number">` and if the value is `null`, both `minus` and `plus` set the `min` value, so we can do the same.

2021-11-30 16:05 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    _controller?.removeListener(_controllerListener);
Listener should be removed from `_effectiveController`.

2021-12-02 09:43 UTC, Sevastyan approved these changes
LGTM

2021-12-02 09:50 UTC, ookami-kb requested changes

2021-12-02 09:50 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    late final int newValue;
You don't need to use `late` here.

2021-12-02 09:50 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    late final int newValue;
You don't need to use `late` here.

2021-12-02 09:50 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +    _updateController(_value);
Since we cannot have both `initialValue` and `controller`, do we need this here?

2021-12-02 09:50 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
I'm not sure about this.

Since we report `null` values (when empty or NaN), shouldn't we also report out-of-range values either as `null`? WDYT?

2021-12-02 10:17 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +    _updateController(_value);
Nope, but anyway i discovered a bug now. When then `controller` is set and have some value the `validation error` is shown.

2021-12-02 10:25 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +    _updateController(_value);
@ookami-kb Can be fixed by adding 
```
WidgetsBinding.instance!.addPostFrameCallback((_) {
      widget.onChanged(_value);
 });
```
into `initState` but i dont like it

2021-12-02 11:59 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +    _updateController(_value);
This will fix the validation error popping but for some reason the `_value` is still null.

2021-12-02 14:28 UTC, chaeMil commented
@ookami-kb Dont ask me, it works like this...

2021-12-02 20:36 UTC, Sevastyan commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
As a user, I'd prefer if I'm not disturbed with out-of-range values on my `onChanged` callback. I might have logic connected to values that are `null` (field empty, or NaN), so reporting some out-of-range *number* as `null` is not what I expect. Out-of-range should not happen, so it should not be reported.

But if we want to be precise, I would introduce a union and report it to `onChanged`:

```
number
out-of-range number
null
NaN
```

And that is an over-engineering.

2021-12-03 13:10 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
This actually seems like a nice solution. WDYT @ookami-kb?

2021-12-06 09:28 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
ping @ookami-kb so how about adding this union?

2021-12-06 10:10 UTC, ookami-kb commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
AS for me, this union doesn't make much sense.

We need to track the fact that out-of-range value was entered (e.g. in Commander the price shouldn't stay the same when changing the amount from 50 to 500, otherwise it would be confusing), but we don't really need the exact reason why the value is invalid (and it will make the usage more complex since you would have to unwrap the value).

If the exact invalid value is needed, you can just provide the controller and get the raw entered value.

2021-12-06 10:18 UTC, chaeMil commented on optimus/lib/src/number_picker/number_picker.dart
> +                  (value == null || value >= min && value <= max)) {
So lets just call `onChange` on every change even if its out of range and the rest leave up to user to use provided controller, right?

2021-12-07 09:42 UTC, chaeMil commented
@ookami-kb yeah nice idea :)

2021-12-07 09:48 UTC, ookami-kb approved these changes

2021-12-07 09:49 UTC, merged