:zap: [RND-43391] StepBar component part 1
MewsSystems/mews-flutter pull request #18
Opened 2021-02-18 13:25 UTC by chaeMil

#### Summary

Added basic structure for `StepBar`

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-02-18 15:24 UTC, Gladkowski approved these changes

2021-02-18 16:19 UTC, ookami-kb requested changes
From the design description I think that horizontal layout should stretch the spacer items, so the stepper itself is full width. It now looks compact:

![image](https://user-images.githubusercontent.com/853356/108386706-3092cb00-720d-11eb-84e8-aa5b17de4a24.png)


Vertical layout looks weird:

<img width="400px" src="https://user-images.githubusercontent.com/853356/108386778-43a59b00-720d-11eb-99cc-892aafcd6c5d.png" />

2021-02-18 16:20 UTC, chaeMil commented on optimus/lib/src/step_bar.dart
> +  final double _itemMinWidth = 112;
Ok will update that, the vertical layout is now not using any breakpoints you need to set it manually, will add that.

2021-02-23 12:44 UTC, Gladkowski approved these changes

2021-02-24 10:48 UTC, ookami-kb approved these changes

2021-02-24 10:48 UTC, merged