fix(optimus): RenderBox.size: Null check operator used on a null value
MewsSystems/mews-flutter pull request #187
Opened 2022-03-03 08:59 UTC by chaeMil

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-03-07 14:53 UTC, ookami-kb requested changes

2022-03-07 14:53 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +    if (renderObject is! RenderBox || !renderObject.hasSize) return _savedRect;
`_savedRect` uses `_calculateRect` for initial value. It can lead to the infinite recursive call.

2022-03-21 18:28 UTC, ookami-kb commented
@chaeMil any progress?

2022-03-22 14:53 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
Why in that case it should become `null` later?

2022-03-24 09:22 UTC, chaeMil commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
@ookami-kb ping

2022-03-24 10:14 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
I don't like these implicit assumptions about "shouldn't be null". Can we initialize it to let's say empty `Rect`? Will it have some visual glitches?

2022-03-24 10:16 UTC, chaeMil commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
I think that the pop up part will go above (in term of z-axis) the button it self and cover it. I will try ;)

2022-03-24 13:37 UTC, chaeMil commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9150597/159927978-e01be9d0-c5c5-4f35-be2a-a7ca05ea340d.png">
Basically it will cover the button itself. Dont mind the offset in storybook its like this always. We can probably do fallback like this.

2022-03-28 08:19 UTC, chaeMil commented
ping @ookami-kb

2022-03-28 08:26 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
This is how it looks for me:

![image](https://user-images.githubusercontent.com/853356/160357426-11d042fd-5292-4f69-a444-44c5ca707808.png)

> Dont mind the offset in storybook its like this always.

It's really weird and should be fixed in that case.

2022-03-28 08:27 UTC, chaeMil commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
Ok i will look into it, but the solution with empty `Rect` could work right?

2022-03-28 08:37 UTC, chaeMil commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
Yeaht it looks the same for me without the empty `Rect`

2022-03-28 12:01 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
Yep, I think empty Rect should work. Let's just create a separate issue for incorrect rendering in the storybook.

2022-03-28 12:01 UTC, ookami-kb requested changes

2022-03-28 12:01 UTC, ookami-kb commented on optimus/lib/src/common/dropdown.dart
> +  // shouldn't be null since its called right after widget creation
This comment is now obsolete.

2022-03-28 12:57 UTC, ookami-kb approved these changes

2022-03-28 13:00 UTC, merged