feat(optimus)!: [RND-103442] Added new variants for Tags
MewsSystems/mews-flutter pull request #195
Opened 2022-05-09 06:19 UTC by witwash

#### Summary
 [RND-103442](https://mews.myjetbrains.com/youtrack/issue/RND-103442)
Added missing variants for the Tag component.
BREAKING CHANGE: Bold/Subtle variants are replaced with OptimusTag (system, prev. bold) and OptimusCategoricalTag (data, prev. subtle). The signature of OptumusTag was changed.

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-05-09 11:19 UTC, ookami-kb commented
@witwash the build is failing.

2022-05-10 09:17 UTC, ookami-kb requested changes

2022-05-10 09:17 UTC, ookami-kb commented on optimus/lib/src/tag.dart
> +/// displaying categorical data.
Add extra line after this line.

2022-05-10 09:17 UTC, ookami-kb commented on optimus/lib/src/tag.dart
> +///
Remove this extra line.

2022-05-10 09:17 UTC, ookami-kb commented on optimus/lib/src/tag.dart
> +  Color get _borderColor {
Let's rather convert them to extensions on `OptimusCategoricalColorOption`.

2022-05-11 09:50 UTC, ookami-kb commented
@witwash please also add the screenshot of the storybook to the PR description – it's easier to get the context of the issue.

2022-05-11 10:34 UTC, witwash commented
Done.

p.s. Is it me or does dark mode look off? It's less readable

2022-05-11 12:43 UTC, ookami-kb commented
@witwash yeah, I think dark mode looks weird. Can you please confirm it with UX guys?

2022-05-11 13:06 UTC, witwash commented
Sure thing. Will keep you updated.

2022-05-12 11:38 UTC, witwash commented
<details>
<summary>New Dark Colors </summary>
<img width="601" alt="Screenshot 2022-05-12 at 13 33 59" src="https://user-images.githubusercontent.com/9210422/168066090-81dbdb25-1e9a-4cbe-804a-83b3ba95bb05.png">

</details>

2022-05-12 14:40 UTC, ookami-kb commented
@witwash please update the PR description with new screenshots

2022-05-13 09:23 UTC, merged