feat(optimus): [RND-103047] Added OptimusNotification
MewsSystems/mews-flutter pull request #204
Opened 2022-05-17 08:48 UTC by witwash

#### Summary

Added OptimusNotification.

<details>
<summary>Screenshots</summary>
<img width="575" alt="Screenshot 2022-05-17 at 10 36 38" src="https://user-images.githubusercontent.com/9210422/168768678-ec8f3d60-0494-4cb0-88a6-fc23f7f8ff61.png">
<img width="544" alt="Screenshot 2022-05-17 at 10 36 47" src="https://user-images.githubusercontent.com/9210422/168768684-a7133830-d07b-4f95-bebd-90e7a5773449.png">
<img width="644" alt="Screenshot 2022-05-17 at 10 36 52" src="https://user-images.githubusercontent.com/9210422/168768689-bc4f9476-245f-4cfe-8157-8aa96158e16a.png">
<img width="559" alt="Screenshot 2022-05-17 at 10 36 56" src="https://user-images.githubusercontent.com/9210422/168768693-fa8cad0e-78a3-4c83-bc5f-5239c1d53b4b.png">
<img width="571" alt="Screenshot 2022-05-17 at 10 37 15" src="https://user-images.githubusercontent.com/9210422/168768696-2fc00f1d-96a0-4f1f-9793-f21401aca388.png">

</details>

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

The next step will be RND-104514.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-05-18 07:54 UTC, Sevastyan requested changes
What about extracting most important bits of a build Widget method into functions (or Widgets) to aid readability?

![g964](https://user-images.githubusercontent.com/23047178/168987033-22ad52d7-aed3-4306-819d-ef8790ad9245.png)

2022-05-18 07:54 UTC, Sevastyan commented on optimus/lib/src/notification.dart
> +const int _kMaxLinesLink = 1;
I don't think we should use `_k` prefix.
@ookami-kb what's the convention in this project on this?

2022-05-18 07:54 UTC, Sevastyan commented on optimus/lib/src/notification.dart
> +class OptimusNotification extends StatelessWidget {
Why the most important piece starts on line `75`? Can we move enums and extensions to the end of the file?

2022-05-18 07:54 UTC, Sevastyan commented on optimus/lib/src/notification.dart
> +/// Notification are used for showing brief and concise message that
Typo: "Notification **is**".

2022-05-18 07:54 UTC, Sevastyan commented on optimus/lib/src/notification.dart
> +    this.description,
Nitpick: I'd rather name it `body` so it goes nicely with `title`.

```
title
body
```

2022-05-18 07:54 UTC, Sevastyan commented on optimus/lib/src/notification.dart
> +    this.onDismiss,
Nitpick.
`onLinkPressed` is in the past tense, but `onDismiss` is not. Let's make it more consistent with `onDismissed`.

2022-05-18 09:13 UTC, witwash commented on optimus/lib/src/notification.dart
> +const int _kMaxLinesLink = 1;
I guess you are right. I saw it in a few places (`expansion_tile.dart` and `optimus_icons.dart`), but most constants are named without `_k`: `spacing.dart` `border_radius.dart` etc.

2022-05-18 09:50 UTC, witwash commented on optimus/lib/src/notification.dart
> +class OptimusNotification extends StatelessWidget {
I left the notification variant enum at the top, but extensions are at the bottom now.

2022-05-19 09:54 UTC, ookami-kb requested changes

2022-05-19 09:54 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +/// Describes a certain type of notification with its semantical meaning.
Add blank line after the first sentence.

2022-05-19 09:54 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +///Notification is used for showing a brief and concise message that
Add space between `///` and text.

2022-05-19 09:54 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +  final VoidCallback? onDismissed;
Let's use the same approach as in default button – if it's dismissible, `onDismissed` shouldn't be `null`. That means that `isDismissible` parameter is not needed.

2022-05-19 09:54 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +  double getPadding() {
Use getter instead.

2022-05-19 09:54 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
Use getter.

2022-05-19 11:36 UTC, witwash commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
Do you mean to replace the entire extension on `OptimusNotificatioVariant` and move them to getters or just that one?

2022-05-19 12:21 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
I mean just changing this one to `IconData get bannerIcon`.

2022-05-19 12:26 UTC, witwash commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
Could you please elaborate on that? Why only `getBannerIcon`? So I'd spot cases like that by myself in the future.

2022-05-19 12:30 UTC, ookami-kb commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
It turns out that we have the info on when to avoid getters, but not on when to use them :) https://github.com/MewsSystems/tech-mo/wiki/Mews-styleguide-for-Flutter-apps#getters-feel-faster-than-methods

In general, our undocumented (yet) style preference is to use the getter instead of `get*` method without parameters if it doesn't conflict with the above-mentioned style guide rule.

2022-05-19 12:48 UTC, alboiuvlad29 commented
I feel like, for a notification widget, it should have some sort of animation. Fade in/out with some curves or some slide in/out from the corner. And maybe I'm missing the code somewhere, but a public method like `showOptimusNotification(context, builder)` should be made available, similarly to what flutter provides (`showDialog`, `showBottomSheet`, `showOptimusDialog`)

2022-05-19 12:49 UTC, witwash commented
Animations and stacking will be implemented in [RND-104514](https://mews.myjetbrains.com/youtrack/issue/RND-104514)

2022-05-19 12:50 UTC, ookami-kb commented
+1 for `showOptimusNotification`.

2022-05-19 12:50 UTC, witwash commented on optimus/lib/src/notification.dart
> +  IconData getBannerIcon() {
OK, I get it. Thanks

2022-05-24 06:41 UTC, witwash commented
It's still WIP as showing a notification is tightly connected with follow-up issue RND-104514, and I don't see how I can implement one without another. I think I will close this one and will split it into several, smaller PRs. What is the recommended way of doing it?

2022-05-24 09:31 UTC, closed without merging

2022-05-24 09:37 UTC, ookami-kb commented
@witwash you can do the notification widget only, and showcase it in storybook as a normal widget.