chore(kiosk_mode): [RND-106334] move watchKioskMode implementation on platform side (android)
MewsSystems/mews-flutter pull request #210
Opened 2022-05-25 10:42 UTC by alboiuvlad29

#### Summary

RND-106334

Based on [this discussion ](https://github.com/MewsSystems/mews-flutter/pull/205#discussion_r878016846), this PR moved the implementation watchKioskMode periodic checks for android to the platform side.

The advantages are:
- no inconsistencies between android and iOS plugin, both use the EventChannel
- the stream will not emit the same value again if the mode hasn't changed

For better visibility, the android implementation has been extracted in functions. 

#### Testing steps

1. Listen to `watchKioskMode` stream on Android
2. Confirm that an event is not being sent every `androidQueryPeriod` like before, and only when kiosk mode actually changes
3. Confirm that `androidQueryPeriod` changes the checking period on the platform level

#### Follow-up issues

No.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-05-30 07:40 UTC, Sevastyan requested changes
This is not a `chore`, but  a fully-fledged `feat`.

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        eventSink = null
also do
```kotlin
eventSink?.endOfStream()
```

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +import java.util.*
Don't do this. Do this:

```
import java.util.Timer
```

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +            val newIsKioskModeState = isKioskMode()
I strongly suggest using

```
currentState
previousState
```

Reading `isKioskMode` in the name is just distracting.

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +typealias KioskModeHandler = () -> Boolean?
Don't use `typedef` and don't declare the return type as nullable.

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
Better to pass this value to the constructor of `KioskModeStreamHandler`. Otherwise, there is this knowledge spread about platform arguments that really should be kept to the `FlutterPlugin` only.

2022-05-30 07:40 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +                }
Don't post anything to the UI thread here. Just call a callback function (to be declared in the constructor).

2022-06-06 08:23 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +                }
No way around it. A callback exposed to `KioskModePlugin` class will not really help. This is the point where a new value is sent to the stream, but this can only be accomplished on the UI thread since `setStreamHandler` is declared with`  @UiThread` annotation. This should be the logic of `KioskModeStreamHandler`.

2022-06-06 08:29 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
I do not agree with this. The parameter is not passed by a method channel, but by the event channel when the broadcast stream is started and listened to. All the logic is self contained within the `KioskModeStreamHandler`. While I am also not that happy with "magic" variables, potentially I could make this class constant.

2022-06-08 07:43 UTC, Sevastyan requested changes

2022-06-08 10:50 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
> The parameter is passed to the platform no matter what kind of channel that is.

How is that? The parameter is just passed to this specific event channel, in this case with the name `com.mews.kiosk_mode/kiosk_mode_stream`. It doesn't make sense to send unrelated arguments to all channels. Then, from platform side `KioskModeStreamHandler` should be the only one handling anything related to this particular event channel. I don't see why we would have to mix this.

```dart
    _eventChannel.receiveBroadcastStream(
      {'androidQueryPeriod': androidQueryPeriod.inMilliseconds},
    ).
```

2022-06-08 10:53 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
As for your other comment, this is how other platforms do it:
https://github.com/fluttercommunity/plus_plugins/blob/e81d039d34cee4cb898962880c46c13de4278a83/packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java
 ```kotlin 
 Runnable runnable = () -> events.success(connectivity.getNetworkType());
 mainHandler.post(runnable);
```

2022-06-08 13:35 UTC, Sevastyan requested changes

2022-06-08 13:53 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
I see your point. But for this case the plugin is specifically made for Android, so saying that it has nothing to do with Android seems a bit erroneous, as this would be the point where the native host would be notified of changes. I think just having `KioskModeStreamHandler` as a black box makes a bit more sense, as in "plug-it" and forget it approach. We just know it's a handler for a particular channel, so no need to also query for parameters there.
 @ookami-kb  What do you think?

2022-06-09 22:24 UTC, ookami-kb commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
> +        val isInKioskMode = when (service.lockTaskModeState) {
I would rather inline it.

2022-06-09 22:24 UTC, ookami-kb commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
`getQueryPeriodMilliseconds` as a constructor parameter makes no sense to me, it makes the solution less readable, and I don't really see what it is needed for. To hide the knowledge that the actual parameter on Flutter side is called `androidQueryPeriod`? Well, the arguments are passed to the `onListen` method anyway, so it makes total sense to process them there, why should `KioskModePlugin` know about it?

2022-06-10 06:17 UTC, Sevastyan commented
@ookami-kb

> why should KioskModePlugin know about it?

It is better to keep knowledge of the parameters in one place. Especially in this case when we don't event have a constants for their names.

2022-06-13 11:17 UTC, alboiuvlad29 commented
I agree more with @ookami-kb about this, and this is a pattern similarly seen in other packages. There is no need for argument parameter names to be kept in one place, in the plugin file. Other packages  have declared StreamHandlers within the plugin file, but to me this makes things less readable and should be in a separate file. Not sure what other argument to bring to the table but I'm keen to find out what @ookami-kb can say about this, and hopefully yo move this PR further.

2022-06-13 12:26 UTC, ookami-kb commented
> It is better to keep knowledge of the parameters in one place. Especially in this case when we don't event have a constants for their names.

The parameters are not related to the plugin in general. They are specific to watching the Kiosk mode, so it doesn't make sense for the whole plugin to know about them.

2022-06-13 12:27 UTC, ookami-kb approved these changes

2022-06-14 07:00 UTC, Sevastyan requested changes

2022-06-14 07:05 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +        val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
This line doesn't work, I tried it initially:
`arguments as Map<*, *>)["androidQueryPeriod"] as Long`. It throws saying you can't cast int to long.

2022-06-14 08:01 UTC, Sevastyan approved these changes

2022-06-14 08:10 UTC, Sevastyan commented
ping @ookami-kb

2022-06-14 08:33 UTC, merged