feat(optimus): [RND-103050] Add Logo component to mobile implementation
MewsSystems/mews-flutter pull request #215
Opened 2022-06-01 12:35 UTC by witwash

#### Summary
RND-103050
Added Mews Logo component. The logo component has specified margins and recommended placement options. Had to reuse the Flutter Icon class with some changes, because the default one does not support non-squared icons. Details:  https://github.com/flutter/flutter/issues/99830.
<details>
<summary>Screenshots</summary>

![Screenshot 2022-06-01 at 14 41 20](https://user-images.githubusercontent.com/9210422/171406832-d462f897-3c1e-4fe1-ac1e-488ea3bdacb5.png)
![Screenshot 2022-06-01 at 14 41 04](https://user-images.githubusercontent.com/9210422/171406957-574ef877-7ea3-4507-889c-502e7f298f47.png)
</details>

#### Testing steps

Check if the component is fulfilling design system specifications.

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-06-01 13:38 UTC, chaeMil approved these changes

2022-06-02 10:29 UTC, ookami-kb requested changes
Also, add the documentation to `OptimusMewsLogo` and enums.

2022-06-02 10:29 UTC, ookami-kb commented on optimus/lib/src/logo.dart
> +  Widget get _icon {
```diff
diff --git a/optimus/lib/src/logo.dart b/optimus/lib/src/logo.dart
index 8bb1d21..bb3e424 100644
--- a/optimus/lib/src/logo.dart
+++ b/optimus/lib/src/logo.dart
@@ -29,20 +29,12 @@ class OptimusMewsLogo extends StatelessWidget {
   final OptimusMewsLogoColorVariant _colorVariant;
   final OptimusMewsLogoAlignVariant _alignVariant;
 
-  Widget get _icon {
+  IconData get _logoIcon {
     switch (_logoVariant) {
       case OptimusMewsLogoVariant.wordmark:
-        return _NonSquaredIcon(
-          OptimusIcons.mews_logo,
-          size: _size,
-          color: _color,
-        );
+        return OptimusIcons.mews_logo;
       case OptimusMewsLogoVariant.logomark:
-        return _NonSquaredIcon(
-          OptimusIcons.mews_logo_small,
-          size: _size,
-          color: _color,
-        );
+        return OptimusIcons.mews_logo_small;
     }
   }
 
@@ -78,8 +70,14 @@ class OptimusMewsLogo extends StatelessWidget {
   }
 
   @override
-  Widget build(BuildContext context) =>
-      Container(margin: _margin, child: _icon);
+  Widget build(BuildContext context) => Container(
+        margin: _margin,
+        child: _NonSquaredIcon(
+          _logoIcon,
+          size: _size,
+          color: _color,
+        ),
+      );
 }
 
 /// Copy of Flutter Icon, but it does not limit icon shape to square.
```

2022-06-03 09:20 UTC, ookami-kb approved these changes
@witwash I've switched to initializing formals for `OptimusMewsLogo`. We don't usually make widget's final properties private, as it's simpler and this encapsulation doesn't make that much sense (as the opposite to BLoCs).

2022-06-03 09:23 UTC, merged