feat(optimus): [RND-103474] Update Date picker component
MewsSystems/mews-flutter pull request #222
Opened 2022-06-14 12:41 UTC by witwash

#### Summary

RND-103474

Updated date picker story to display picked time and AM/PM. The date picker is now called when tapping on the calendar icon, which is present by default. **Clear All** button is now visible if it is enabled and the selected date is not `null`.

<details>
<summary>Screenshot</summary>

![CleanShot 2022-06-14 at 14 38 03@2x](https://user-images.githubusercontent.com/9210422/173578846-ca77dcba-3329-46f4-851b-6b542bc753f3.png)
</details>

#### Testing steps

Open Storybook with DateTime picker story. Change the date and time. Clear all should be visible if it is enabled and the selected date is not `null`.

#### Follow-up issues

None

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-06-14 15:09 UTC, kamil-grzadziela commented on storybook/lib/stories/date_time_field.dart
> +            return '${d.day}/${d.month}/${d.year} ${hours.format()}:${d.minute.format()} $am';
I would suggest using https://api.flutter.dev/flutter/intl/DateFormat-class.html

` formatDateTime: (d) =>  DateFormat('dd/MM/yyyy hh:mm a').format(d)`

2022-06-14 15:26 UTC, kamil-grzadziela approved these changes

2022-06-15 13:03 UTC, chaeMil approved these changes

2022-06-20 20:15 UTC, witwash commented
@ookami-kb ping

2022-06-21 12:31 UTC, ookami-kb requested changes
One small point, otherwise LGTM.

2022-06-21 12:31 UTC, ookami-kb commented on optimus/lib/src/date_time_field.dart
> +  late bool isClearVisible;
```dart
bool _isClearVisible = false;
```

`late` is error-prone and in general, should be avoided.

2022-06-21 14:42 UTC, merged