feat(optimus): [RND-103475] Added Checkbox nested variant
MewsSystems/mews-flutter pull request #223
Opened 2022-06-20 10:32 UTC by witwash

#### Summary

Added nested checkboxes to Optimus. 

<details>
<summary>Screenshot</summary>

![CleanShot 2022-06-20 at 11 20 02](https://user-images.githubusercontent.com/9210422/174569902-a4509c88-5f98-4a1f-b800-3ce21f54c0a2.png)

</details>

#### Testing steps

- Open the nested checkboxes story and test it the parent checkbox represents the group state correctly.
	-  Checked - all children are checked.
	-  Unchecked - none of the children is checked.
	-  Dash - some children are checked.  

#### Follow-up issues

None

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-06-28 09:39 UTC, witwash commented
Bump

2022-06-29 08:20 UTC, witwash commented
@alboiuvlad29 can you please take a look?

2022-06-29 10:38 UTC, alboiuvlad29 requested changes
From my point of view, I think it would make more sense to map `isChecked` and `tristate` to some internal state. I.e., 
```dart
enum _CheckboxState {checked, unchecked, undetermined }
```
This would be easier to handle in code.

2022-06-29 10:44 UTC, witwash commented on optimus/lib/src/checkbox/checkbox.dart
> +  }
Sure thing, I was taking the inspiration from the origin tho :-/ : https://github.com/flutter/flutter/blob/676cefaaff197f27424942307668886253e1ec35/packages/flutter/lib/src/material/checkbox.dart#L212

2022-06-29 10:46 UTC, alboiuvlad29 commented on optimus/lib/src/checkbox/checkbox.dart
> +  }
They are using MaterialState. It's ok to pass tristate as parameter, but use another internal state that "checked" and 'tristate' can be mapped to.

2022-07-01 13:12 UTC, witwash commented
@alboiuvlad29 ping 👀

2022-07-01 19:21 UTC, alboiuvlad29 approved these changes

2022-07-01 19:21 UTC, alboiuvlad29 commented on optimus/lib/src/checkbox/checkbox.dart
> +  }
This is fine, but prefer using Widgets rather than function builders when necessary in the future. And I think this is something we should emphasise in our docs, as I see we we rely in quite a couple of places on unnecessary builder methods. 
```dart
class _CheckboxIcon extends StatelessWidget {
const _CheckboxIcon({this.icon);

final IconData? icon;

@override
Widget build(BuildContext context) => icon == null ? const SizedBox() : Center(
             child: Icon(
               _checkboxState.icon,
               size: 10,
               color: theme.colors.neutral0,
             ),
           );
}
```

2022-07-18 08:07 UTC, alboiuvlad29 approved these changes

2022-07-19 10:38 UTC, ookami-kb commented
I meant here a different setup, from the user point of view you should be able to change checkboxes into a nested group by simply wrapping them into `OptimusCheckboxGroup`, smth like this:

```dart
OptimusCheckboxGroup(
  children: [
    OptimusCheckbox(),
    OptimusCheckbox(),
    OptimusCheckbox(),
  ],
)
```

Everything else should be done automatically.

2022-07-22 12:41 UTC, witwash commented
@ookami-kb I was trying to come up with the way I could do this with the way you mentioned. Each time I was stopped because I needed more control over the `OptimusCheckbox`es, therefore they need to be created inside the widget from some kind of model and not passed as a ready `Widget`. Can you please elaborate on the way you see it?

2022-07-25 08:50 UTC, ookami-kb commented
@witwash let's have a call about it.

2022-08-01 11:20 UTC, witwash commented
@ookami-kb can you please take a look?

2022-08-02 05:48 UTC, witwash commented
@ookami-kb after our call I made some changes. Now it's a mere wrapper that will change all the children inside it and will call their `onChange`, if the `parent` changes.

2022-08-03 09:14 UTC, ookami-kb commented on optimus/lib/src/checkbox/nested_checkbox.dart
> +                isEnabled: widget.isEnabled,
Not needed, you already wrap the whole group into `OptimusEnabled`.

2022-08-03 09:14 UTC, ookami-kb commented on optimus/lib/src/checkbox/nested_checkbox.dart
> +                    child.onChanged.call(value);
```dart
child.onChanged(value);
```

2022-08-03 09:16 UTC, ookami-kb requested changes
One more thing: right now refreshing the group relies on the fact that changing the value of the single checkbox will call `setState` of the whole group widget thus leading to rebuild. I would say it should be more explicit – changing checkbox should explicitly invalidate the state of the group.

2022-08-08 10:14 UTC, witwash commented
@ookami-kb can you look at it again, please?

2022-08-08 10:26 UTC, ookami-kb approved these changes

2022-08-08 10:26 UTC, merged