feat(optimus)!: [RND-103473] Update Input component
MewsSystems/mews-flutter pull request #228
Opened 2022-07-05 14:24 UTC by witwash

#### Summary

RND-103473

Updated Input component to match mews.design and the design of the web (component)[https://apps.mews.com/mews-ui-storybook/release/0.748.2/index.html?path=/story/form-input-inputfield--default]. 

Breaking changes:
- By design `prefix` and `suffix` should be just text widgets (with applied text style), that are displayed closest to the text input on both sides.
- Previous `prefix` and `suffix` are now `leadingWidget` and `tailingWidget`. They can be used for displaying a leading icon or leading image as well as for displaying a tailing icon or tailing widget, as is declared on mews.design.

Visually these changes will not break anything, but some changes are required so the usage is consistent across all products.

<details> <summary>Screenshots</summary>

<img width="577" alt="CleanShot 2022-07-05 at 16 01 33@2x" src="https://user-images.githubusercontent.com/9210422/177349692-1aaf9210-cb00-4673-a058-06d33f32a35f.png">
<img width="506" alt="CleanShot 2022-07-05 at 16 01 21@2x" src="https://user-images.githubusercontent.com/9210422/177349702-8db2a2bd-549e-40e4-85a2-1ec4540fe4de.png">
<img width="507" alt="CleanShot 2022-07-05 at 16 01 08@2x" src="https://user-images.githubusercontent.com/9210422/177349698-b3cc894b-c79e-487d-b53b-a9612e59d656.png">
<img width="493" alt="CleanShot 2022-07-05 at 16 01 15@2x" src="https://user-images.githubusercontent.com/9210422/177349706-ef138d17-5736-494c-ab90-7ad5bf3365e8.png">

</details>

Other changes:
- Focused state has a priority over the error state (the focused field is always colored as focused even if there is an error)
- Password show/hide input is a variation of the tailing widget and if enabled should replace it.
- The loading icon is neither a suffix text nor a tailing widget, so it should not replace them.
- Clear button is now visible when activated and the input field has non-empty input.
- Updated Storybook. 

#### Testing steps

1. Open Storybook
2. OptimusInputField component should match the screenshots above (position of widgets inside the component).

#### Follow-up issues

RND-111259 - update usage in code.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-07-07 08:31 UTC, alboiuvlad29 requested changes

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/chat/optimus_chat_input.dart
> +        tailingWidget: OptimusEnabled(
Should it not be `trailing` ? 
I also think we should remove `Widget`, seems unnecessary.

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/common/field_wrapper.dart
> +
Extract to widget

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/form/input_form_field.dart
> +    Widget? leadingWidget,
We should remove `Widget` from name. `leading` would be enough.

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
> +/// interactive functionality. If [isPasswordField] is true, passwordButton will
This comment should be added to the field `trailing`. It makes a bit more sense to warn the developers at that point, that their widget may be overridden by password button. Same with the other parameters. Doesn't seem that necessary to mention their usage in the class docs.

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
> +  bool get _isShowClearAll =>
`_shouldShowClearAllButton`

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
> +
Extract to widget

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
> +  }
Extract to widget. You could use a `const SizedBox()` rather than returning null.

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
>    }
Extract to widget.

2022-07-07 08:31 UTC, alboiuvlad29 commented on optimus/lib/src/input_field.dart
> +    setState(() {});
Why is this necesarry?

2022-07-12 08:59 UTC, witwash commented on optimus/lib/src/input_field.dart
> +  }
It's deliberate. It has to be null, otherwise, `FieldWrapper` would count with it and will add padding.

2022-07-12 09:01 UTC, witwash commented on optimus/lib/src/input_field.dart
> +    setState(() {});
Removed the second one and reused it for both controllers. Overall it's here for making sure `ClearAllButton` is visible if the input is not empty.

2022-07-19 10:32 UTC, ookami-kb commented
According to mews.design, we just have left detail and right detail:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/853356/179730171-41343eed-3972-4fea-aeef-292020dec5b3.png">

What about having just `leading` and `trailing` parameters accepting `Widget[]` and applying default text styles?

2022-07-19 12:26 UTC, witwash commented
Having just `leading` and `trailing` parameters is good, but not enough. @tomhirsch emphasised on icons/images and prefixes having a strict order. `[<leading icon/image>, <prefix>, user input, <suffix>, <clear all>, <loader>, <trailing icon/image>]`, like it's implemented for the [web](https://apps.mews.com/mews-ui-storybook/release/0.744.1/index.html?path=/story/form-input-inputfield--default&knob-Caption=Caption&knob-Caption%20icon=integration_partners&knob-Clearable=true&knob-Has%20show%20password%20toggle=true&knob-Helper=Caption%20text,%20description%20or%20notification&knob-Indicative%20icon=search&knob-Interactive%20icon=visibility&knob-Label=Label&knob-Loading=true&knob-Placeholder=Placeholder&knob-Prefix=prefx&knob-Required=true&knob-Size=medium&knob-Suffix=sfx&knob-Variant=default&knob-size=medium).
<details><summary>Screenshots</summary>

<img width="620" alt="CleanShot 2022-07-19 at 12 42 10@2x" src="https://user-images.githubusercontent.com/9210422/179749748-b93dc632-85e6-45d4-b353-f82d6dafaacd.png">


</details>

2022-07-21 08:12 UTC, witwash commented
@ookami-kb ping

2022-07-25 08:31 UTC, ookami-kb approved these changes

2022-07-25 08:31 UTC, merged