feat(optimus): [RND-103479] Add alignment prop to typography components
MewsSystems/mews-flutter pull request #242
Opened 2022-08-02 05:29 UTC by witwash

#### Summary

- Added missing `align` property to the typography components. By default, it will resolve to the `TextAlign.left`, so it should not bring any visual changes as previously it was set to `TextAlign.start` anyway.
- Updated stories

<details><summary>Screenshots</summary>

`OptimusTypographyAlignment.left`

![CleanShot 2022-08-02 at 07 26 51@2x](https://user-images.githubusercontent.com/9210422/182298529-99548084-8d76-498d-a31f-a2740cca2cea.png)

`OptimusTypographyAlignment.right`

![CleanShot 2022-08-02 at 07 26 58@2x](https://user-images.githubusercontent.com/9210422/182298534-1c02a401-be11-407b-b1bf-17cf0bc68704.png)

`OptimusTypographyAlignment.center`

![CleanShot 2022-08-02 at 07 27 09@2x](https://user-images.githubusercontent.com/9210422/182298540-4198577e-90fd-44dc-8e47-8ef794c9bb7b.png)

</details> 

#### Testing steps

1. Open storybook
2. Open any typography coponent
3. Change it to very long text
4. Change the `align` property and check if it is displaying correctly.

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-08-03 08:05 UTC, alboiuvlad29 requested changes

2022-08-03 08:05 UTC, alboiuvlad29 commented on optimus/lib/src/typography/alignment.dart
> +}
Is this wrapper really necessary ? Why not use `TextAlign` as is?

2022-08-03 09:05 UTC, witwash commented on optimus/lib/src/typography/alignment.dart
> +}
Because the design is defined for the `left`, `center` and `right`. `TextAlign` has `start` and `end` on top of that.

2022-08-03 15:21 UTC, witwash commented on optimus/lib/src/typography/alignment.dart
> +}
@alboiuvlad29 do you think it's better to skip the wrapper and simply pass the `TextAlign`? I did it this way because for example the `OptimusStack` there is an `OptimusStackAlignment`, which is doing pretty much the same thing and the idea is to limit the choice to the ones that are allowed. 

```
extension on OptimusStackAlignment {
  CrossAxisAlignment get crossAxisAlignment {
    switch (this) {
      case OptimusStackAlignment.start:
        return CrossAxisAlignment.start;
      case OptimusStackAlignment.center:
        return CrossAxisAlignment.center;
      case OptimusStackAlignment.end:
        return CrossAxisAlignment.end;
    }
  }

  MainAxisAlignment get mainAxisAlignment {
    switch (this) {
      case OptimusStackAlignment.start:
        return MainAxisAlignment.start;
      case OptimusStackAlignment.center:
        return MainAxisAlignment.center;
      case OptimusStackAlignment.end:
        return MainAxisAlignment.end;
    }
  }
}
```

2022-08-04 07:48 UTC, alboiuvlad29 commented on optimus/lib/src/typography/alignment.dart
> +}
For me, it makes more sense to be universal and use types that flutter provides, for easier swapping, but depends what others think. @ookami-kb thoughts?

2022-08-08 10:13 UTC, witwash commented
@ookami-kb can you please look at it?

2022-08-08 10:24 UTC, ookami-kb commented on optimus/lib/src/typography/alignment.dart
> +}
I agree with @alboiuvlad29, let's rather use `TextAlign`.

The main reason for `OptimusStackAlignment`, IIRC, was for the user not to care about `CrossAxisAlignment` vs `MainAxisAlignment`.

2022-08-08 10:33 UTC, witwash commented on optimus/lib/src/typography/alignment.dart
> +}
Done ;)

2022-08-08 16:01 UTC, alboiuvlad29 requested changes

2022-08-08 16:01 UTC, alboiuvlad29 commented on optimus/lib/src/typography/highlight.dart
> +
Use macros for repeated documentation:
https://pub.dev/packages/dartdoc#macros

The `The alignment of the highlight.` should be generalised to something like `The alignment of the text within this widget` or similar.

You can have something like:
```dart
/// {@template optimus.components.text.textAlignment}
///  The alignment of the text within this widget.
///
/// Defaults to [TextAlign.left].
/// {@endtemplate}
```

and use it:
```diff
- /// The alignment of the highlight.
- ///
- /// Defaults to [TextAlign.left].
+ /// {@macro optimus.components.text.textAlignment}
 final TextAlign align;
```

2022-08-09 12:58 UTC, alboiuvlad29 approved these changes

2022-08-10 11:14 UTC, ookami-kb approved these changes

2022-08-10 11:17 UTC, ookami-kb requested changes
Shouldn't this `align` property be nullable? So that by default, we don't override this property, and it will be taken from the upper text style?

2022-08-10 12:50 UTC, witwash commented
@ookami-kb done ;)

2022-08-11 09:56 UTC, alboiuvlad29 commented on optimus/lib/src/typography/caption.dart
>    /// Defaults to [TextAlign.left].
@witwash Please update this. The default provided by flutter in Text widget is `TextAlign.start`, but maybe we shouldn't mention this here since it may change with the framework?

2022-08-11 10:03 UTC, witwash commented on optimus/lib/src/typography/caption.dart
>    /// Defaults to [TextAlign.left].
@alboiuvlad29 

The documentation is correct, `align` will be set to `TextAlign.left` if no value is given.

Yes, the default of the `Text` widget is `TextAlign.start`, but `OptimusTypography` default is `TextAlign.left`. `start` and `end` are there for the RTL languages and we don't support those yet anyway

2022-08-11 11:14 UTC, ookami-kb commented on optimus/lib/src/typography/caption.dart
>    /// Defaults to [TextAlign.left].
But Flutter supports them, I think we should rather default to `TextAlign.start`. For LTR languages that would make no difference, but for RTL languages it will be automatically supported.

2022-08-11 14:05 UTC, ookami-kb approved these changes

2022-08-11 14:05 UTC, merged