feat(optimus): Add DateFormatter
MewsSystems/mews-flutter pull request #253
Opened 2022-09-01 10:12 UTC by witwash

#### Summary

The first part of the RND-114990

Added `DateFormatter` with tests. 

#### Testing steps

- `DateFormatter` is covered with tests. 

#### Follow-up issues

- Will add the component itself in part 2.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-09-02 09:16 UTC, ookami-kb requested changes

2022-09-02 09:16 UTC, ookami-kb commented on optimus/test/date_formatter_test.dart
> +    testWidgets('Adding valid input', (tester) async {
Tests can be simplified. You don't need widget tests at all here, you're testing just a formatting functionality. Something like this:

```dart
test('valid input', () {
  final sut = DateFormatter(
    mask: '##-##-####',
    placeholder: 'DD-MM-YYYY',
    userInput: [],
  );

  const oldValue = TextEditingValue(
    text: '',
    selection: TextSelection.collapsed(offset: 0),
  );
  const newValue = TextEditingValue(
    text: '1',
    selection: TextSelection.collapsed(offset: 1),
  );
  final actual = sut.formatEditUpdate(oldValue, newValue);

  expect(
    actual,
    const TextEditingValue(
      text: '1D-MM-YYYY',
      selection: TextSelection.collapsed(offset: 1),
    ),
  );
});
```

2022-09-02 09:16 UTC, ookami-kb commented on optimus/lib/src/form/date_formatter.dart
> +  final String placeholder;
As a user, I shouldn't bother with both mask and placeholder. I should just enter the mask as `DD-MM-YYYY` and the widget should do everything else internally.

2022-09-02 09:16 UTC, ookami-kb commented on optimus/lib/src/form/date_formatter.dart
> +  final RegExp? allowedDigits;
I don't think this is needed.

2022-09-02 09:16 UTC, ookami-kb commented on optimus/lib/src/form/date_formatter.dart
> +  final VoidCallback? onUserInputChanged;
There should be no callback like this. This is a formatted, basically, pure function. It should just format the value.

2022-09-02 09:16 UTC, ookami-kb commented on optimus/lib/src/form/date_formatter.dart
> +    required List<int> userInput,
User shouldn't provide this, it should be done internally if needed.

2022-09-02 09:18 UTC, witwash commented on optimus/lib/src/form/date_formatter.dart
> +  final String placeholder;
It does. You can pass the `DateFormat` to the widget and it will format it and will use it for the `DateFormatter`.

2022-09-02 09:21 UTC, witwash commented on optimus/lib/src/form/date_formatter.dart
> +    required List<int> userInput,
This is the list of positions that were input by the user. All of it is for the `OptimusDateInputField/FormField`, not for the end user.

2022-09-05 07:46 UTC, witwash commented
I reworked the DateInput component. Since we don't support letter input (web doesn't), it can be simplified. Should be more bearable now.

2022-09-05 08:41 UTC, ookami-kb commented on optimus/test/date_formatter_test.dart
> +  testWidgets('Starting with initial value', (tester) async {
Why do you need widget tests at all for `DateFormatter`? It can just be unit tests, as it doesn't make sense to test the input field integration with input formatted – that's what Flutter does.

2022-09-05 08:44 UTC, witwash commented on optimus/test/date_formatter_test.dart
> +  testWidgets('Starting with initial value', (tester) async {
Good point. Will delete it.

2022-09-05 09:55 UTC, ookami-kb commented on optimus/test/date_formatter_test.dart
> +void main() {
Let's further optimize tests code. You can add a helper method:

```dart
@isTest
void testFormat({
  required String format,
  TextEditingValue oldValue = const TextEditingValue(
    text: '',
    selection: TextSelection.collapsed(offset: 0),
  ),
  required TextEditingValue newValue,
  required TextEditingValue expected,
}) {
  test('formats ${newValue.text} according to $format', () {
    final formatter = DateFormatter(placeholder: format);

    expect(formatter.formatEditUpdate(oldValue, newValue), expected);
  });
}
```

And then rewrite tests to smth like that:

```dart
testFormat(
  format: 'DD-MM-YYYY',
  newValue: const TextEditingValue(
    text: '1',
    selection: TextSelection.collapsed(offset: 1),
  ),
  expected: const TextEditingValue(
    text: '1D-MM-YYYY',
    selection: TextSelection.collapsed(offset: 1),
  ),
);
```

2022-09-05 13:49 UTC, ookami-kb commented
@witwash I've done some refactoring. Tests are passing, but please check that I didn't break any logic.

2022-09-05 13:54 UTC, witwash commented
@ookami-kb, thank you.

2022-09-06 07:43 UTC, ookami-kb approved these changes

2022-09-06 07:43 UTC, merged