feat(kiosk_mode): [RND-125108 ] implement `startKioskMode` for iOS
MewsSystems/mews-flutter pull request #275
Opened 2022-11-02 14:00 UTC by alboiuvlad29

#### Summary

This PR adds implementations for `startKioskMode` and `stopKioskMode` on iOS.

- **BREAKING** `stopKioskMode` signature changed to allow querying wether the response was successful or not from iOS
- **BREAKING** `isManagedKiosk` was removed as deemed unnecessary 

From Apple's documentation, the method will work when:
- Device is supervised in Apple Business Manager
- App using this package is allowed to run under Single App Mode

>You can use this method to lock your app into Single App mode and to release it from that mode later. For example, a test-taking app might enter this mode at the beginning of a test and exit it when the user completes the test. Entering Single App mode is supported only for devices that are supervised using Mobile Device Management (MDM), and the app itself must be enabled for this mode by MDM. You must balance each call to enter Single App mode with a call to exit that mode.
Because entering or exiting Single App mode might take some time, this method executes asynchronously and notifies you of the results using the completionHandler block.

https://developer.apple.com/documentation/uikit/uiaccessibility/1615186-requestguidedaccesssession

#### Testing steps

Unfortunately, without having a supervised device, there isn't really a way to test this.  
Functionality was dev-tested with the response from the `completionHandler` mocked.
```swift
 requestGuidedAccessSession(enabled: true, completionHandler: { result($0) })
```
```swift
 requestGuidedAccessSession(enabled: true, completionHandler: { result(!$0) })
```

#### Follow-up issues

No.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-11-02 14:41 UTC, Sevastyan commented
@alboiuvlad29 could you please join forces with @BegovicAmar and find out whether our IT would be able to help testing it with a real Apple Business Manager? If I'm not mistaken, they already have it for company's purposes. And I think it would be wise to have at least one iPad with MDM in QA.

2022-11-02 15:15 UTC, kamil-grzadziela approved these changes

2022-11-02 16:01 UTC, alboiuvlad29 commented
@Sevastyan This cannot be tested separately, in a package, we need to test it in an app. 
Yes we can set up some devices in MDM but for that, we also need a release build.

So I suggest: 
- Let's focus on merging the fictionality in this package that enables us to use it
- Let's create a feature flag and implement this in Kiosk
- We will create a release, and ask for help from IT team to: 1. Help us supervise an iPad from the QA team, 2. Add Kiosk app to allowlist to automatically toggle single app mode.

You can see exactly the same code used in Apple's video here https://developer.apple.com/videos/play/wwdc2022/10152/, seek to 08:40.

2022-11-02 16:05 UTC, Sevastyan approved these changes
LGTM.

2022-11-02 16:39 UTC, alboiuvlad29 commented
ping @ookami-kb

2022-11-02 16:51 UTC, ookami-kb commented
> This cannot be tested separately, in a package, we need to test it in an ap

@alboiuvlad29 why not? There is an example app there.

2022-11-02 16:56 UTC, ookami-kb commented
> BREAKING stopKioskMode signature changed to allow querying wether the response was successful or not from iOS

Switching from `void` to `bool` is not actually a breaking change.

> BREAKING isManagedKiosk was removed as deemed unnecessary

Why? We don't use it, but it can be used by someone else. It doesn't require big efforts to maintain it, so I don't see a reason to remove it.

2022-11-03 16:09 UTC, Sevastyan requested changes

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +              (value) => ScaffoldMessenger.of(context).showSnackBar(
Let's move `then` closure out to some private method. It will ease the reading and comprehension of the UI.

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +              (value) => ScaffoldMessenger.of(context).showSnackBar(
Same here, let's move it to a private method.

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                        : 'Kiosk mode could not be stopped or wasn\'t active to begin with.',
Can we disable the button then, if we are not in kiosk mode?

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                        : 'Kiosk mode could not be stopped or wasn\'t active to begin with.',
Can we disable the button then, if we are not in kiosk mode?

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                        : 'Kiosk mode could not be stopped or wasn\'t active to begin with.',
Can we disable the button then, if we are not in kiosk mode?

2022-11-03 16:09 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                        : 'Kiosk mode could not be stopped or wasn\'t active to begin with.',
Can we disable the button then, if we are not in kiosk mode?

2022-11-04 11:32 UTC, alboiuvlad29 commented on kiosk_mode/example/lib/main.dart
> +                            : 'Kiosk mode could not be started.',
Can MDM actually forbid setting lock task mode on Android? The only times this could be `false` on Android it's when:
1. Activity is null
2. IllegalArgumentException is thrown

2022-11-04 14:33 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                            : 'Kiosk mode could not be started.',
If that's the case, maybe we should add "try again" into that message. So, it's not treated as "it's impossible".

2022-11-04 17:12 UTC, alboiuvlad29 commented on kiosk_mode/example/lib/main.dart
> +                            : 'Kiosk mode could not be started.',
I've added this to the message.

2022-11-06 11:29 UTC, Sevastyan requested changes

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +  }
Why `_showSnackBar` is async? Why not to utilize one line for 

```dart
ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(message)));
```
?

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                                  ? 'Single App mode is supported only for devices that are supervised using Mobile Device Management (MDM) and the app itself must be enabled for this mode by MDM.'
Let's follow some human-friendly line limit. Long literal Strings can be split:

```dart
: Platform.isIOS
    ? 'Single App mode is supported only for devices that are supervised using'
        ' Mobile Device Management (MDM) and the app itself must be enabled for this mode'
        ' by MDM.'
    : 'Kiosk mode could not be started. Please try again.',
```

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                              ? 'Kiosk mode started'
I don't like this. The information about the current mode is already shown by the last Widget (`Current mode: `).

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                                  : 'Kiosk mode could not be started. Please try again.',
Let's not tell anything at all, if we cannot tell anything useful. Don't show the message on Android (actually, on any platform that is not iOS).

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                        .then(_showSnackBar),
Revert changes for "Stop Kiosk Mode" button.

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                child: const Text('Is Managed Kiosk'),
`Check if managed` to keep the language consistent with `Check mode`.

2022-11-06 11:29 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +              ),
```dart
Text('Current mode: ${snapshot.data}'),
```
please.

2022-11-08 10:09 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +    fun setKioskModeState(isInKioskMode: Boolean?) =  postEvent(isInKioskMode)
I'm against exposing this outside of this class. `KioskModeStreamHandler.kt` has only one job: to notify the platform channel of changes in  kiosk mode, let it either be automatic (from timer query) or manual when the switch happened. It's not good to expose this outside of the class where it could be misused. Someone could call `endOfStream` preliminary.

2022-11-08 10:17 UTC, alboiuvlad29 commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
> +            // in this case, it's better to allow calling stopLockTask() than being stuck in kiosk mode
It doesn't make sense, as this would be a regression for iOS - since we can know wether the request was successful or not. On plugin side, someone might want to know wether the request was successful or not. Then it's the duty of the native implementation to respond accordingly. Since Android doesn't provide a way to check this, but reading the documentation the call to stop kiosk mode would fail if it wasn't in kiosk mode to begin with, we can assume the logic above: If the app was in kiosk mode, then it must succeed. Otherwise it would fail

@ookami-kb thoughts?

2022-11-08 10:29 UTC, alboiuvlad29 commented on kiosk_mode/example/lib/main.dart
> +                              ? 'Kiosk mode started'
This is meant to show the usage of this method, it's just an example, after all. `Current mode` shows the behaviour of the stream. Some people perhaps would not rely on that, so showing it like this in the example app is not problematic in any way.

2022-11-08 11:04 UTC, ookami-kb commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
> +            // in this case, it's better to allow calling stopLockTask() than being stuck in kiosk mode
From the user's point of view, I would expect that the result of `stopKioskMode` is `true` if I'm not in kiosk mode anymore after this call. From that point of view, returning `false` if I'm not in kiosk mode, seems weird, it looks as if the call failed and I'm still in kiosk mode.

And yes, if we don't know the result of the call, we can return `null` as a result.

But it's fine if iOS returns strict `bool` if we **can know** the result there.

2022-11-12 13:32 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
> +    fun setKioskModeState(isInKioskMode: Boolean?) =  postEvent(isInKioskMode)
Well, it can be misused even currently - someone can just send whatever he wants down the stream - either `true`, or `false` and it could be even not matching the reality. Let's refactor to this:

<details>
<summary>diff</summary>

```diff
diff --git a/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt b/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
index 0dbcedc..fc4dbde 100644
--- a/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
+++ b/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
@@ -48,7 +48,7 @@ class KioskModePlugin : FlutterPlugin, MethodCallHandler, ActivityAware {
                 try {
                     a.startLockTask()
                     result.success(true)
-                    kioskModeHandler.setKioskModeState(true)
+                    kioskModeHandler.emit()
                 } catch (e: IllegalArgumentException) {
                     result.success(false)
                 }
@@ -61,7 +61,7 @@ class KioskModePlugin : FlutterPlugin, MethodCallHandler, ActivityAware {
         fun stopLockTask() {
             activity?.stopLockTask()
             result.success(true)
-            kioskModeHandler.setKioskModeState(false)
+            kioskModeHandler.emit()
         }
 
         when(isInKioskMode()) {
diff --git a/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt b/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
index 3291b2b..9c74b72 100644
--- a/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
+++ b/kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModeStreamHandler.kt
@@ -7,7 +7,7 @@ import java.util.*
 import kotlin.concurrent.fixedRateTimer
 
 
-class KioskModeStreamHandler(val getKioskModeState: () -> Boolean?) : EventChannel.StreamHandler {
+class KioskModeStreamHandler(private val getKioskModeState: () -> Boolean?) : EventChannel.StreamHandler {
     private var eventSink: EventChannel.EventSink? = null
     private var timer: Timer? = null
     private var previousState: Boolean? = getKioskModeState()
@@ -17,16 +17,7 @@ class KioskModeStreamHandler(val getKioskModeState: () -> Boolean?) : EventChann
         val period: Int = (arguments as Map<*, *>)["androidQueryPeriod"] as Int
         eventSink = events
         timer = fixedRateTimer(period = period.toLong(), daemon = true) {
-           postEvent(getKioskModeState())
-        }
-    }
-
-    private fun postEvent(currentState: Boolean?) {
-        if (currentState != previousState) {
-            previousState = currentState
-            eventSink?.let {
-                mainHandler.post { it.success(currentState) }
-            }
+            emit()
         }
     }
 
@@ -37,5 +28,13 @@ class KioskModeStreamHandler(val getKioskModeState: () -> Boolean?) : EventChann
         timer = null
     }
 
-    fun setKioskModeState(isInKioskMode: Boolean?) =  postEvent(isInKioskMode)
+    fun emit() {
+        val currentState = getKioskModeState()
+        if (currentState != previousState) {
+            previousState = currentState
+            eventSink?.let {
+                mainHandler.post { it.success(currentState) }
+            }
+        }
+    }
 }
```

</details>

2022-11-12 13:32 UTC, Sevastyan commented on kiosk_mode/android/src/main/kotlin/com/mews/kiosk_mode/KioskModePlugin.kt
> +            // in this case, it's better to allow calling stopLockTask() than being stuck in kiosk mode
@alboiuvlad29 Please, revert it.This file is for Android. And on Android it should always be `result.success(null)` - as it was previously.

And I agree with Kirill's comment - I don't expect `false`, if I wasn't in kiosk mode before this call. My intention is to stop kiosk mode, so when I call `stopKioskMode` I should get `true` for when the mode was actually stopped, or nothing happened because there was nothing to stop - in both cases I expect `true` to be returned.

2022-11-12 13:32 UTC, Sevastyan commented on kiosk_mode/lib/kiosk_mode.dart
> +Future<bool> stopKioskMode() => _channel
Make the return `bool` nullable and update the documentation comment. On Android, it should just fire `Activity.stopLockTask()` and return `.success(null)`.

2022-11-12 13:32 UTC, Sevastyan commented on kiosk_mode/example/lib/main.dart
> +                              ? 'Kiosk mode started'
The quality of the code should not depend on whether this is just an example, or something intended for production. If anything, the quality of an example should be elevated, since it's intended for public use.

> Some people perhaps would not rely on that

What do you mean?

My problem with all this is that the information is duplicated.

2022-11-15 15:40 UTC, Sevastyan approved these changes
Changing of `stopKioskMode` signature - in this case changing the return type from `void` to `bool` is not a breaking change. Please, update the description and PR title.

2022-11-16 09:18 UTC, Sevastyan commented
@ookami-kb it's ready to be reviewed by you 🙏🏻

2022-11-16 11:07 UTC, ookami-kb approved these changes

2022-11-16 11:07 UTC, ookami-kb commented on kiosk_mode/example/lib/main.dart
> +        'Kiosk mode could not be stopped or was not active to begin with.',
```suggestion
        'Kiosk mode could not be stopped or was not active.',
```

2022-11-16 11:08 UTC, merged