feat(optimus)!: [RND-126039] Additional changes for date input field
MewsSystems/mews-flutter pull request #276
Opened 2022-11-14 14:56 UTC by alboiuvlad29

#### Summary

See usage in this PR: https://github.com/MewsSystems/tech-mo/pull/1576.

Fixes issue when input from android native keyboard wasn't working.
Allows picker to be changed by provided `value`.

Marking as breaking since `initialValue` has been renamed to `value`.

Thanks @witwash for your help!

#### Testing steps

No.

#### Follow-up issues

No.
#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2022-11-14 15:12 UTC, witwash commented
I've updated the name since there is a breaking change.

2022-11-14 22:35 UTC, witwash approved these changes

2022-11-15 09:25 UTC, alboiuvlad29 commented
ping @ookami-kb  🙏🏻

2022-11-15 16:03 UTC, ookami-kb commented on optimus/lib/src/form/input_field.dart
> +  final ValueChanged<bool>? onKeyboardVisibilityChanged;
Why do you need this parameter?

2022-11-16 09:42 UTC, alboiuvlad29 commented on optimus/lib/src/form/input_field.dart
> +  final ValueChanged<bool>? onKeyboardVisibilityChanged;
It was initially used to update the field value when the keyboard disappeared, but I've updated it to use focus nodes instead.

2022-11-16 11:40 UTC, ookami-kb requested changes

2022-11-16 11:40 UTC, ookami-kb commented on optimus/lib/src/form/date_input_field.dart
> +  FocusNode get _effectiveFocusNode =>
It's not attached to any widget, i.e. it's not used.

2022-11-16 11:40 UTC, ookami-kb commented on optimus/lib/src/form/date_input_field.dart
> +  final ValueChanged<DateTime?>? onEditCompleted;
I don't think that it should be done like this.

First, this is confusing, as there's `onEditingComplete` parameter in default Flutter widgets that behaves differently. 

Second, relying on the focus node doesn't give you the expected behavior. E.g. pressing some button or checkbox will not unfocus the current field.

2022-11-16 11:40 UTC, ookami-kb commented on optimus/lib/src/form/date_input_field.dart
> +    _effectiveFocusNode.dispose();
No, it should never be done like this. You cannot dispose the focus node that was passed as the parameter – you don't own it. Disposing should only be called for internal `_focusNode`, for external nodes only listeners should be removed.

2022-11-16 12:20 UTC, alboiuvlad29 commented on optimus/lib/src/form/date_input_field.dart
> +    _effectiveFocusNode.dispose();
I know, and I would never have done it this way, although for some reason `OptimusInputField` behaves the same so I was just keeping the behaviour similar. I can remove this and we can later on update the widgets to dispose focus nodes by the owner, but this would require changes in all packages using any widget with `OptimusInputField` as a child to remove the expectation that the child will handle disposing parent-provided arguments that need to be disposed.

2022-11-18 13:19 UTC, witwash approved these changes

2022-11-18 13:21 UTC, witwash commented on optimus/lib/src/form/input_field.dart
> +    widget.onClear?.call();
Is `onChanged('')` not sufficient?

2022-11-18 13:51 UTC, Sevastyan reviewed
@witwash Should it validate the input? Like, check that it is actually a date that makes sense?

* `line 9`: it is not a `FormField`.

@alboiuvlad29 I'm failing to understand what this PR is about. Could you describe the change in the PR description, please?

2022-11-18 13:51 UTC, Sevastyan commented on optimus/lib/src/form/date_input_field.dart
> +  /// Function to be called when the input focus was lost or keyboard is hid.
`hid.`? Let's not shorten words.

2022-11-18 13:51 UTC, Sevastyan commented on optimus/lib/src/form/date_input_field.dart
> +  final VoidCallback? onClear;
I don't think the name makes sense, given the things this callback is supposed to be called for, as per the documentation comment.

2022-11-18 14:55 UTC, alboiuvlad29 commented on optimus/lib/src/form/date_input_field.dart
> +  /// Function to be called when the input focus was lost or keyboard is hid.
Has been removed.

2022-11-18 14:55 UTC, alboiuvlad29 commented on optimus/lib/src/form/date_input_field.dart
> +  final VoidCallback? onClear;
Has been removed.

2022-11-18 14:58 UTC, witwash commented on optimus/lib/src/form/date_input_field.dart
> +  /// Function to be called when the input focus was lost or keyboard is hid.
it's not a shortened word, it's my bad grammar :-/

2022-11-18 15:06 UTC, witwash commented
@Sevastyan,

The date is validated on if it's a `DateTime` or not (otherwise it's `null`). It's not validated whether it's a valid date in some certain context. You can validate it with `onSubmit` or `onChange`. We can add a range for the validation if it's necessary.

2022-11-18 15:19 UTC, alboiuvlad29 commented
@Sevastyan Updated the comment. The PR adds 2 things:
1. A fix for native android keyboard, where input wasn't recognised (workaround is commented in code)
2. Allows the field to display values provided by `value` field.

2022-11-20 08:05 UTC, Sevastyan approved these changes
LGTM

2022-11-21 08:58 UTC, alboiuvlad29 commented
@ookami-kb 🙏🏻

2022-11-21 15:01 UTC, ookami-kb approved these changes

2022-11-21 15:02 UTC, merged