feat(storybook): Updated storybook version. Added saving theme.
MewsSystems/mews-flutter pull request #299
Opened 2023-01-23 13:56 UTC by witwash

#### Summary

Updated storybook dependency. Added theme saving.

#### Testing steps

1. Open Storybook.
2. Change the theme.
3. Hot-reload - theme should be saved.

You can test it on the firebase [here](https://witwash-storybook.web.app/#/).

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-01-30 09:19 UTC, ookami-kb requested changes

2023-01-30 09:19 UTC, ookami-kb commented on storybook/lib/main.dart
> +  late Future<ThemeMode> _themeMode;
Can it be final?

2023-01-30 09:19 UTC, ookami-kb commented on storybook/lib/main.dart
> +    final value = prefs.getString('themeMode');
Extract `themMode` to constants.

2023-01-30 09:19 UTC, ookami-kb commented on storybook/lib/main.dart
> +    await prefs.setString('themeMode', themeMode.toString());
I would rather be saving just `name` – it's a little bit more flexible, since doesn't rely on `toString()` implementation and the name of the class.

2023-01-30 17:37 UTC, ookami-kb commented on storybook/lib/main.dart
> +  ThemeMode get toThemeMode {
You can remove hard-coded strings as well with smth like

```dart
ThemeMode.values.firstWhere((e) => e.name == this, orElse: () => ThemeMode.system);
```

2023-01-31 10:28 UTC, ookami-kb commented on storybook/lib/main.dart
> +  ThemeMode get toThemeMode => ThemeMode.values
nitpicking: `toThemeMode` sounds like a method name, so it should rather be `toThemeMode()`.

2023-01-31 11:09 UTC, ookami-kb commented on storybook/pubspec.yaml
> +  shared_preferences: ^2.0.16
Sorry, just noticed another small issue: shouldn't `.lock` file be updated as well?

2023-01-31 11:14 UTC, witwash commented on storybook/pubspec.yaml
> +  shared_preferences: ^2.0.16
https://github.com/MewsSystems/mews-flutter/blob/d94cec7b25865f6669059fe85536d613895b1614/.gitignore#L4 ¯\_(ツ)_/¯

2023-01-31 11:26 UTC, ookami-kb approved these changes

2023-01-31 11:26 UTC, merged