feat(optimus): [RND-162272] Added OptimusTooltip
MewsSystems/mews-flutter pull request #328
Opened 2023-03-10 02:50 UTC by witwash

#### Summary

- Added the `OptimusTooltip` component.
- Added the `OptimusTooltip` story.

<details><summary>Screenshots</summary>

![CleanShot 2023-03-10 at 03 46 25](https://user-images.githubusercontent.com/9210422/224210797-81fccd00-db8c-4e20-ab3d-803a7431d72a.gif)
</details>

#### Testing steps

- Check the tooltip story and try out exposed options.

#### Follow-up issues

- [RND-165619] - whole PR was getting out of hand so I've split it into two parts. The second part will contain the `OptimusTooltipWrapper` that would define the behavior and position of the `OptimusTooltip`.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-03-13 18:00 UTC, witwash commented
@ookami-kb,
Can you please look at this one? I have a follow-up ready and waiting 🙏

2023-03-15 11:30 UTC, witwash commented
@ookami-kb,
ping

2023-03-15 11:33 UTC, ookami-kb requested changes

2023-03-15 11:33 UTC, ookami-kb commented on optimus/lib/src/tooltip/tooltip_arrow.dart
> +class TooltipArrow extends StatelessWidget {
If the arrow is drawn separately, there's a thin line between arrow and the main shape, it's visible even on screenshots. I would say, the whole shape should be drawn in custom painter.

2023-03-15 13:49 UTC, witwash commented
@ookami-kb, 
fixed. The new look: 
<details><summary>Preview</summary>

![CleanShot 2023-03-15 at 14 40 25](https://user-images.githubusercontent.com/9210422/225328502-07ed91b3-3a7d-4a5f-bfa5-2159cd73274c.gif)


</details>

2023-03-17 12:26 UTC, witwash commented
@ookami-kb, ping

2023-03-20 08:45 UTC, ookami-kb approved these changes

2023-03-20 08:45 UTC, merged