:zap: [RND-49612] Add theming for InputField and FieldWrapper
MewsSystems/mews-flutter pull request #34
Opened 2021-02-25 12:54 UTC by chaeMil

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-02-25 13:59 UTC, Gladkowski requested changes

2021-02-25 13:59 UTC, Gladkowski commented on optimus/lib/src/field_wrapper.dart
> +  OptimusThemeData get _theme => OptimusTheme.of(context);
I would replace it with `ThemeGetter` mixin.
`class _FieldWrapper extends State<FieldWrapper> with ThemeGetter `

2021-02-25 13:59 UTC, Gladkowski commented on optimus/lib/src/input_field.dart
> +  OptimusThemeData get _theme => OptimusTheme.of(context);
Same here. I would replace it with mixin.
`class _OptimusInputFieldState extends State<OptimusInputField> with ThemeGetter`

2021-02-25 13:59 UTC, Gladkowski commented on optimus/lib/src/input_field.dart
> +    final color = _theme.isDark
I would replace it with 
```
    final color = theme.isDark
        ? theme.colors.neutral0t64
        : theme.colors.secondaryTextColor;
```

2021-02-25 13:59 UTC, Gladkowski commented on optimus/lib/src/input_field.dart
> +    final color = _theme.isDark
I would replace it with 
```
              cursorColor: _theme.isDark
                  ? theme.colors.neutral200
                  : theme.colors.basic,
```

2021-02-25 14:27 UTC, Gladkowski requested changes
I would replace all the `OptimusLightColors` and `OptimusDarkColors` to `theme.colors`.

2021-02-25 14:29 UTC, Gladkowski commented on optimus/lib/src/input_field.dart
> +        : OptimusLightColors.neutral900;
I would replace it with `theme.colors.defaultTextColor` neutral1000 is new default text color

2021-02-26 07:46 UTC, Gladkowski approved these changes

2021-02-26 09:52 UTC, ookami-kb commented on optimus/lib/src/input_field.dart
> +        theme.isDark ? theme.colors.neutral0 : theme.colors.neutral1000;
Shouldn't it use `defaultTextColor`/`inverseTextColor` as well?

2021-02-26 22:18 UTC, merged