feat(optimus): [RND-166993] Add inline input error for the OptimusTextInput
MewsSystems/mews-flutter pull request #341
Opened 2023-04-05 13:29 UTC by witwash

[RND-166993] 

#### Summary

- Added an inline error option (is using an OptimusTooltip to show it).
- Updated a story.

<details><summary>Video</summary>

![CleanShot 2023-04-05 at 15 17 39](https://user-images.githubusercontent.com/9210422/230093436-ff28bbb5-c02b-49af-b3a9-9325ee203502.gif)

</details> 

#### Testing steps

1. Open the `Input` story
2. Set an error and enable the inline error option.
3. Test with other screen sizes.

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-04-05 13:40 UTC, witwash commented
Look like the .gif compression ate the color of the right border 🤔 
here is the screenshot as a proof that it is still there 

<details><summary>Screenshot</summary>

![CleanShot 2023-04-05 at 15 39 11](https://user-images.githubusercontent.com/9210422/230098018-58b079ef-61a6-40d1-8d02-dfdbce0baeac.png)

</details>

2023-04-11 10:07 UTC, witwash commented
@ookami-kb,
ping

2023-04-12 09:00 UTC, ookami-kb requested changes

2023-04-12 09:18 UTC, witwash commented on optimus/lib/src/common/field_wrapper.dart
> +    this.usingInlineError = false,
How about `bottom` and `inline`? Or more verbose:

```
enum OptimusInputErrorVariant {
  bottomHint,
  inlineTooltip,
}
```

2023-04-12 09:40 UTC, ookami-kb commented on optimus/lib/src/common/field_wrapper.dart
> +    this.usingInlineError = false,
Yeah, both options sound fine to me 👍

2023-04-12 11:26 UTC, ookami-kb commented on optimus/lib/src/common/field_wrapper.dart
> +  final bool usingInlineError;
This is still using `bool` parameter.

2023-04-12 11:41 UTC, ookami-kb approved these changes

2023-04-12 11:42 UTC, witwash commented
Shoot, you were quick. I did a change to the naming

2023-04-12 11:42 UTC, ookami-kb commented
Yeah, saw it, LGTM.

2023-04-12 11:46 UTC, merged