feat(optimus): [RND-164813] Add a grouping support to the Select Input component
MewsSystems/mews-flutter pull request #367
Opened 2023-05-26 09:12 UTC by witwash

[RND-164813]

#### Summary

- added grouping support to `SelectInput` and `SearchInput`
- updated docs
- updated stories

<details><summary>Screenshots</summary>

![CleanShot 2023-05-25 at 23 06 01](https://github.com/MewsSystems/mews-flutter/assets/9210422/60258846-478b-476b-96d6-f6fb78d6897f)

![CleanShot 2023-05-25 at 23 05 46](https://github.com/MewsSystems/mews-flutter/assets/9210422/d8f3da4f-172a-42f8-94e7-dfe171724037)

![CleanShot 2023-05-26 at 11 11 03](https://github.com/MewsSystems/mews-flutter/assets/9210422/eca11cc8-a973-4294-96b5-522a03ec6ea7)

![CleanShot 2023-05-26 at 11 11 59](https://github.com/MewsSystems/mews-flutter/assets/9210422/e62694f2-5d18-4626-9326-ecfab10e939f)

</details>

#### Testing steps

- open Select Input story
- enable grouping
- check if the component is displayed correctly

#### Follow-up issues

None.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-05-30 10:24 UTC, ookami-kb requested changes

2023-05-30 10:24 UTC, ookami-kb commented on optimus/lib/src/dropdown/dropdown.dart
> +      shrinkWrap: true,
Don't use `shrinkWrap`, it will kill performance on bigger lists.

2023-05-30 10:24 UTC, ookami-kb commented on optimus/lib/src/dropdown/dropdown.dart
> +          return _GroupDecorator(
I don't like this "flat" structure and magic with indexes. Can we do wrapping instead? E.g. something like this:

```
0 -> [List Tile 0]
1 -> [Column: [Header] [List Tile 1]]
2 -> [List Tile 2]
3 -> [List Tile 3]
```

So that indices in item builder map 1:1 to indices in the source list.

2023-06-06 09:31 UTC, witwash commented
@ookami-kb, ping

2023-06-07 08:59 UTC, ookami-kb approved these changes

2023-06-07 08:59 UTC, merged