feat: [RND-177241] Enable theming using tokens
MewsSystems/mews-flutter pull request #372
Opened 2023-06-14 11:26 UTC by witwash

#### Summary

- Updated `OptimusTheme` and added an `OptimusTokens tokens` property, which will hold all tokens for light/dark theme.
- `OptimusTokens` is basically a `ThemeExtension` and I'm using `tailor` for the code generation.
- `OptimusTokens` could be overwritten with `copyWith`, this will enable custom theming. You need to wrap it with `OptimusTheme` and provide your custom `OptimusTokens` for light and dark themes.

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

- Testing?
- More code generation, from the design-tokens PR, to make this process less error-prone.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-06-14 11:27 UTC, witwash commented
@ookami-kb I'd like to hear your thoughts before I continue working on it 🙏

2023-06-15 12:19 UTC, witwash commented
@ookami-kb, ping

2023-06-15 12:21 UTC, ookami-kb commented
Sorry, forgot to add a comment. Yeah, in general, it makes sense to me,

2023-06-20 09:26 UTC, witwash commented
`analyzer` dep is locked to `5.12.0`, cuz there is a breaking change in the minor update, and code generation is not working as intended.

2023-06-22 08:42 UTC, ookami-kb requested changes

2023-06-22 08:42 UTC, ookami-kb commented on optimus/pubspec.yaml
> +  analyzer: 5.12.0
Is that a conflict because of `theme_tailor`? What do we need to remove this override?

2023-06-22 08:42 UTC, ookami-kb commented on optimus/lib/src/theme/optimus_tokens.dart
Where do these data come from? Is it created manually?

2023-06-22 08:42 UTC, ookami-kb commented on optimus/lib/src/theme/optimus_tokens.tailor.dart
Add this file to `.gitattributes` please.

2023-06-22 09:07 UTC, witwash commented on optimus/lib/src/theme/optimus_tokens.dart
I'm working on a script that will generate this one with the PR from the `design-tokens`. For now, yes, it was created manually.

2023-06-22 09:09 UTC, witwash commented on optimus/pubspec.yaml
> +  analyzer: 5.12.0
yep, it's because `theme_tailor` didn't update to fix the `analyzer` breaking change

2023-06-22 09:35 UTC, witwash commented on optimus/pubspec.yaml
> +  analyzer: 5.12.0
I saw that `freezed` last update fixed that problem. I will check it out and create a PR to `theme_tailor` with the fix.

2023-06-22 09:38 UTC, witwash commented on optimus/pubspec.yaml
> +  analyzer: 5.12.0
https://github.com/rrousselGit/freezed/pull/921, look like it was merged as a temporary fix before the author will come up with a better solution. I'll do my best, at worst I'll start a discussion about this bug ;)

2023-06-22 09:55 UTC, ookami-kb approved these changes

2023-06-22 09:55 UTC, merged