feat: Update rules set
MewsSystems/mews-flutter pull request #409
Opened 2023-08-10 16:28 UTC by witwash

#### Summary

- added some rules from the DCM 1.7 and 1.8
- removed deprecated rules
- added commented rules, so it's more clear what is missed and what is a deliberate choice we've made.

#### Questionable rules (disabled for now)
- `avoid-negated-conditions `- up for the debate
- `avoid-importing-entrypoint-exports` - basically the idea is good, but we need to move `optimus_icons.dart` somewhere and I'm not sure how would it work with `tech-mo` projects
- `enum-constants-ordering` - don't think the team would like to bother with something like this
- `avoid-unused-instances` - is triggering on `Futures.delayed`

#### Testing steps

None

#### Follow-up issues

None

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-08-14 11:54 UTC, witwash commented on mews_pedantic/lib/analysis_options.yaml
> -    - iterable_contains_unrelated_type
those were deprecated 

<details><summary>spoiler</summary>

![CleanShot 2023-08-14 at 13 53 55](https://github.com/MewsSystems/mews-flutter/assets/9210422/6466fc2b-46cd-4183-8e50-1f66fa9c8259)

</details>

2023-08-14 11:56 UTC, witwash commented on optimus/lib/src/form/input_form_field.dart
> +              // ignore: avoid-accessing-other-classes-private-members, have to access it somehow
was not sure how to deal with it here 🤔

2023-08-15 10:50 UTC, ookami-kb requested changes

2023-08-15 10:50 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    - avoid-accessing-other-classes-private-members
Not sure if need this 🤔
They are not private, they are *library*-private, so I would say it's fine if they are accessed within the library.

2023-08-15 10:50 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    - map-keys-ordering
I would remove this, pure styling issue, doesn't make much sense to me.

2023-08-15 10:50 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    - prefer-first
We had this, but it didn't prove to be useful. `foo.last` makes sense because it's usually what you mean, but for the first one, in many places, it looks artificial, especially when it's something like `foo.first + foo[1]`.

2023-08-15 10:50 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    - prefer-named-boolean-parameters
Yeah, let's add `ignore-single`.

2023-08-15 13:49 UTC, ookami-kb commented
@witwash the build is failing

2023-08-15 14:27 UTC, witwash commented
@ookami-kb, ready

2023-08-15 14:29 UTC, ookami-kb commented
@witwash the build is failing

2023-08-15 14:32 UTC, witwash commented
@ookami-kb, fixed

2023-08-15 14:34 UTC, ookami-kb approved these changes

2023-08-15 14:34 UTC, merged