feat!: Upgrade to DCM 1.11.0
MewsSystems/mews-flutter pull request #470
Opened 2023-11-09 11:25 UTC by witwash

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-11-09 11:29 UTC, witwash commented
@ookami-kb, WDYT about enabling [prefer-correct-handler-name](https://dcm.dev/docs/rules/common/prefer-correct-handler-name/) and [prefer-correct-callback-field-name](https://dcm.dev/docs/rules/common/prefer-correct-callback-field-name)? I know that is something that we agreed on, but are we ready to enforce it? :D

2023-11-09 11:31 UTC, witwash commented
And what about [avoid-collection-mutating-methods](https://dcm.dev/docs/rules/common/avoid-collection-mutating-methods)? I think we could enable it with local only 🤔

2023-11-09 12:29 UTC, witwash commented
Well, I think we should enable `handler` one, but leave the `callback-field-name` turned off. We have plenty of `typedef` functions that are reported by this and I don't think that renaming the to `"on...." ` is making any sense.

2023-11-10 12:34 UTC, ookami-kb commented
> Well, I think we should enable `handler` one, but leave the `callback-field-name` turned off. We have plenty of `typedef` functions that are reported by this and I don't think that renaming the to `"on...." ` is making any sense.

Makes sense to me. @alboiuvlad29 @chaeMil @Sevastyan your input?

2023-11-10 12:40 UTC, ookami-kb requested changes

2023-11-10 12:40 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    # - prefer-explicit-type-arguments
Let's enable this one instead of `avoid-inferrable-type-arguments`. I was specifically requesting for this rule for cases with `get_it` and `provider` where omitting type arguments can lead to confusing and fragile code.

2023-11-10 12:40 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    # - match-lib-folder-structure
I would enable this (yeah, it will have a lot of triggers in our code).

2023-11-10 12:40 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    - prefer-addition-subtraction-assignments
I don't think this rule is useful, I would disable it.

2023-11-10 12:40 UTC, ookami-kb commented on mews_pedantic/lib/analysis_options.yaml
> +    # - prefer-specific-cases-first
Looks useful, why disabling it?

2023-11-10 13:40 UTC, witwash commented on mews_pedantic/lib/analysis_options.yaml
> +    # - prefer-specific-cases-first
Was stuck on the question "what is specific?" and had a feeling we would have been something like enum ordering enforce. I'll enable it and we'll see.

2023-11-10 14:05 UTC, Sevastyan commented
> > Well, I think we should enable `handler` one, but leave the `callback-field-name` turned off. We have plenty of `typedef` functions that are reported by this and I don't think that renaming the to `"on...." ` is making any sense.
> 
> Makes sense to me. @alboiuvlad29 @chaeMil @Sevastyan your input?

I agree. In most cases having `on....` for typedefs doesn't make sense. Let's ignore.

2023-11-14 11:11 UTC, ookami-kb commented on optimus/lib/src/typography/title.dart
> +// ignore_for_file: prefer-correct-handler-name
Why does it need to be ignored here?

2023-11-14 11:27 UTC, witwash commented on optimus/lib/src/typography/title.dart
> +// ignore_for_file: prefer-correct-handler-name
It was triggering on the preset resolver. I've added a comment on why it is ignored there.

![CleanShot 2023-11-14 at 12 24 13](https://github.com/MewsSystems/mews-flutter/assets/9210422/e459e04b-3090-4656-afa0-ecc8feb7e79e)

2023-11-14 11:56 UTC, ookami-kb commented on optimus/lib/src/typography/title.dart
> +// ignore_for_file: prefer-correct-handler-name
Discussed with DCM author, global functions will be excluded from this check in the next releases.

For now, let's ignore them inline instead of file-level ignoring, otherwise, this ignore won't be marked as obsolete when the rule is updated.

2023-11-14 12:42 UTC, witwash commented on optimus/lib/src/typography/title.dart
> +// ignore_for_file: prefer-correct-handler-name
Done

2023-11-14 13:12 UTC, ookami-kb approved these changes

2023-11-14 13:15 UTC, merged