ci: Add tokens PR action
MewsSystems/mews-flutter pull request #475
Opened 2023-11-28 11:06 UTC by witwash

#### Summary

Added an action that would trigger on push in `design-tokens-**` branch. This action will create a PR to `master`.

This action will ensure we have the latest version of tokens from [design-tokens](https://github.com/MewsSystems/design-tokens). Right now we have an action that is committing new files to `design-tokens-${version}` branch. This action will create a PR and generate files that were touched by the tokens update. 

#### Testing steps

We'll need to check whether the trigger is working correctly and the PR is created.

#### Follow-up issues

~~Set up an action that would regenerate `theme_tailor` files in this same PR.~~ done

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2023-11-29 18:12 UTC, witwash commented
@ookami-kb, WDYT? 🤔

2023-12-01 10:57 UTC, ookami-kb requested changes

2023-12-01 10:57 UTC, ookami-kb commented on .github/workflows/tokens-pr.yml
> +        uses: repo-sync/pull-request@v2
Let's rather use GitHub CLI, it's pre-installed on action runners: https://cli.github.com/manual/gh_pr_create

2023-12-01 10:57 UTC, ookami-kb commented on .github/workflows/tokens-pr.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
Why do we need a separate action for that? Isn't it just a couple lines of code?

2023-12-01 11:11 UTC, witwash commented on .github/workflows/tokens-pr.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
For no particular reason tbh. I wrote it with commands at first, then I looked at the action and it felt cleaner

2023-12-01 11:54 UTC, ookami-kb commented on .github/workflows/tokens-pr.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
I would rather avoid using 3rd party actions unless they bring a lot of benefits.

2023-12-04 01:42 UTC, witwash commented on .github/workflows/tokens-pr.yml
> +          git config --local user.email "tech.account@mewssystems.com"
Do we have a user that we should use here? In `design-tokens` repo we use `tech.account@mewssystems.com`

2023-12-04 12:02 UTC, merged