Add segmented control
MewsSystems/mews-flutter pull request #60
Opened 2021-03-22 18:01 UTC by Gladkowski

#### Summary

@chaeMil @ookami-kb I'm experiencing issues with borders.

![borders](https://user-images.githubusercontent.com/23431508/112035623-04d27000-8b40-11eb-89a5-d723f1d18be5.jpg)

The initial idea was to create a container with just 3 borders, but it turns out [it is not possible when radius is non-null](https://github.com/flutter/flutter/issues/12583).

I tried ClipRect but it leaves empty space instead of border that I am trying to wipe.

Any ideas on how to solve it without custom border drawing tool are welcome. Thanks ;)

2021-03-23 15:24 UTC, Gladkowski commented
@ookami-kb @chaeMil ready to review

2021-03-24 08:59 UTC, chaeMil approved these changes

2021-03-24 10:41 UTC, ookami-kb requested changes

2021-03-24 10:41 UTC, ookami-kb commented on optimus/lib/src/segmented_control/segmented_control.dart
> +  Color get _textColor => _isSelected
According to design, `textColor` for light theme is always `neutral900` for both selected and non-selected.

2021-03-24 10:41 UTC, ookami-kb commented on optimus/lib/src/segmented_control/segmented_control.dart
> +  final ValueChanged<T> onChanged;
`onItemSelected` as for select control?

2021-03-24 10:41 UTC, ookami-kb commented on optimus/lib/src/segmented_control/segmented_control.dart
> +  int _selectedItemIndex = 0;
The component shouldn't maintain its state. The selected value comes from the client.

2021-03-24 10:41 UTC, ookami-kb commented on optimus/lib/src/segmented_control/wrapper.dart
> +                ignoring: true,
It's `true` by default.

2021-03-24 10:41 UTC, ookami-kb commented on optimus/lib/src/segmented_control/segmented_control.dart
> +    required this.value,
I would limit the value. I guess segmented control should *always* have some value out of provided, so that one value is always "on".

So maybe an assert that checks that value is in provided items?

2021-03-25 10:51 UTC, ookami-kb commented
@Gladkowski @chaeMil I've pushed some small updates, please check.

2021-03-25 12:14 UTC, Gladkowski commented
> @Gladkowski @chaeMil I've pushed some small updates, please check.

Checked. Looks good.

2021-03-25 13:42 UTC, ookami-kb approved these changes

2021-03-25 13:44 UTC, merged