feat!: Upgrade to DCM 1.17.0
MewsSystems/mews-flutter pull request #608
Opened 2024-05-13 08:53 UTC by witwash

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against Jira issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2024-05-13 09:06 UTC, ookami-kb commented
@witwash links to the rules in PR description are broken.

2024-05-13 09:11 UTC, alboiuvlad29 commented
`avoid-collection-equality-checks` we mostly use immutable lists everywhere which does deep equality comparison. Does this check consider that? If not we should probably disable it as it will be a pain to deal with this check afterwards.

2024-05-13 09:12 UTC, alboiuvlad29 commented
I also don't see any benefit to `avoid-multi-assignment` as well. There are some places we do this on purpose.

2024-05-13 09:15 UTC, ookami-kb commented
@alboiuvlad29 I cannot find any usage of multi-assignment.

2024-05-13 09:16 UTC, witwash commented
I can see how neglecting `avoid-multi-assignment` can lead to less readable code 🤔. Who are you saving that one/two lines for, @alboiuvlad29? 😄

2024-05-13 09:29 UTC, alboiuvlad29 commented
Never-mind, it was a different usage I had in mind and this isn't it regarding `avoid-multi-assignment`. Sorry about that. 😅

2024-05-13 10:15 UTC, ookami-kb requested changes

2024-05-13 10:15 UTC, ookami-kb commented on kiosk_mode/example/lib/main.dart
> +  VoidCallback? _onStartPressed(KioskMode? mode) => switch (mode) {
Inline these methods, otherwise, the name is confusing. It's not a handler method, it's a method that creates a handler.

2024-05-13 10:21 UTC, ookami-kb approved these changes

2024-05-13 10:22 UTC, witwash commented
@chaeMil 👀

2024-05-13 12:48 UTC, chaeMil approved these changes

2024-05-14 10:04 UTC, witwash commented
@alboiuvlad29, 🙏

2024-05-14 10:05 UTC, alboiuvlad29 approved these changes

2024-05-14 10:05 UTC, merged