kiosk_mode: android:attr/lStar not found when assembling in release mode #681
MewsSystems/mews-flutter pull request #689
Opened 2024-10-01 06:02 UTC by ijascookee

Updated android versions

2024-10-01 09:05 UTC, chaeMil commented
cc @ookami-kb @Sevastyan @alboiuvlad29

2024-10-01 09:11 UTC, alboiuvlad29 requested changes
Thank you very much for the contribution! 🙏

There's one change from my side, otherwise looks good to me.

2024-10-01 09:11 UTC, alboiuvlad29 commented on kiosk_mode/pubspec.yaml
This file should not be changed. It's automatically updated by Melos when we publish the package.

2024-10-04 05:51 UTC, manav-zf commented on kiosk_mode/pubspec.yaml
Please add this fix

2024-10-04 05:52 UTC, manav-zf commented
Please merge the fix @ijascookee  @chaeMil @alboiuvlad29

2024-10-07 15:13 UTC, alboiuvlad29 commented
Closing in favour of https://github.com/MewsSystems/mews-flutter/pull/695.

2024-10-07 15:13 UTC, closed without merging