fix(optimus): Add `isRequired` to multiple field components
MewsSystems/mews-flutter pull request #73
Opened 2021-05-03 11:47 UTC by Sevastyan

#### Summary

1. Added `isRequired` support to `OptimusCheckbox`. Updated the story.

2. Added `isRequired` support to `OptimusCheckboxGroup`. Updated the story.

3. Added `isRequired` support to `OptimusDateTimeField`.

4. Re-written `OptimusCheckboxFormField`, because it was not efficiently
implemented. 

5. Added `isRequired` support to `OptimusSelectFormField`.

6. Changed type of `OptimusGroupItem::label` from `Widget` to `String`, because
it should be `Text` Widget always, as per Mews Design. But mainly because it
made all this `isRequired` support possible for checkboxes.

7. Updated `form` story.

I've also moved `isRequired` next to `label` property in some places. This is
because `isRequired` affects `label`, and it is more convenient to have them
together because of it.

#### Testing steps

No.

#### Follow-up issues

No.

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-05-03 14:18 UTC, Gladkowski approved these changes

2021-05-03 14:23 UTC, ookami-kb requested changes

2021-05-03 14:23 UTC, ookami-kb commented on optimus/lib/src/checkbox/checkbox.dart
> +  final String label;
We cannot change it to `String`. We're already using it as a widget, e.g. for displaying terms and conditions as text with links.

2021-05-03 14:23 UTC, ookami-kb commented on optimus/lib/src/group_item.dart
> +  final String label;
Same here, it can be useful to provide some custom widget, and we're already doing it by providing `TranslatedText`.

2021-05-03 14:34 UTC, Gladkowski commented on optimus/lib/src/checkbox/checkbox.dart
> +  final String label;
Oops, forgot about that. Good point

2021-05-04 08:30 UTC, chaeMil approved these changes

2021-05-04 09:05 UTC, Sevastyan commented
Closing as the solution is not ideal:

* asterisk is not looking good for multi-line text .
* it may be even worth, as the label is `Widget`, which can be anything.

Clients can add asterisk themselves, if they so desire.

2021-05-04 09:05 UTC, closed without merging