:zap: [RND-43393] Develop Banner component
MewsSystems/mews-flutter pull request #8
Opened 2021-02-03 13:35 UTC by chaeMil

Since we don't have proper icons for `OptimusBannerVariant.warning` and `OptimusBannerVariant.error` yet, I created two TODOs there.

2021-02-03 14:27 UTC, ookami-kb commented
@chaeMil 

- warning: `OptimusIcons.problematic`
- error: `OptimusIcons.blacklist`

2021-02-03 14:31 UTC, Gladkowski requested changes

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +                        child: Icon(_icon, size: 20, color: _iconColor),
I think that size 20 is not particularly correct. So I suggest replacing it with `OptimusIcon`, with medium size and relevant OptimusColorOption.

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +        return Colors.white;
`return OptimusColors.basic0;`

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +        return Colors.black;
`return OptimusColors.basic1000;`

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +                  child: GestureDetector(
I would replace it with something like that:
```
 // TODO(): Replace with OptimusIconButton when ready
 // https://mews.myjetbrains.com/youtrack/issue/RND-47422
IconButton(
                splashRadius: 24,
                padding: EdgeInsets.zero,
                onPressed: () => Navigator.pop(context),
                icon: const OptimusIcon(iconData: OptimusIcons.cross_close),
              ),
```

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +        return OptimusIcons.disable; // TODO(MM): add warning icon
`return OptimusIcons.problematic;`

2021-02-03 14:31 UTC, Gladkowski commented on optimus/lib/src/banner.dart
> +        return OptimusIcons.disable; // TODO(MM): update icon
`return OptimusIcons.blacklist;`

2021-02-03 14:45 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +                  child: GestureDetector(
`IconButton` is already merged, so it can be used here.

2021-02-04 08:08 UTC, Gladkowski approved these changes

2021-02-04 10:20 UTC, ookami-kb requested changes

2021-02-04 10:20 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +  final bool showIcon;
Let's name it as `hasIcon` – booleans starting with `is*` or `has*` are better readable. `showIcon` sounds like a method name.

2021-02-04 10:20 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +  double get _bannerHeight => _hasAdditionalDescription ? 68 : 40;
I don't think we should hard-code the size.

2021-02-04 10:20 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +  final String additionalDescription;
I would rename `content` to `title` and `additionalDescription` to `description`. Also, `description` can be made `Widget` type.

2021-02-04 10:20 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +          child: Stack(
Let's make it a row with an expanded title and close button.

2021-02-04 10:20 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +enum OptimusBannerVariant {
Do we actually need it as a separate `enum`? It matches 1:1 with `OptimusColorOption` and I think it has the same semantic meaning.

2021-02-04 10:30 UTC, chaeMil commented on optimus/lib/src/banner.dart
> +enum OptimusBannerVariant {
`OptimusColorOption` has `basic` which is not present here. That why i created that enum.

2021-02-04 14:40 UTC, chaeMil commented on optimus/lib/src/banner.dart
> +          child: Stack(
Im not sure how to properly place the close button then. The `OptimusIconButton` is too big and then it expands the whole `Banner` more than in the design, this is what i mean: 
![image](https://user-images.githubusercontent.com/9150597/106908086-3eb9f500-66ff-11eb-9e83-2fbcc4dd145d.png)

2021-02-04 15:47 UTC, ookami-kb commented on optimus/lib/src/banner.dart
> +          child: Stack(
A title shouldn't be that close to the top border, there's padding there:
![image](https://user-images.githubusercontent.com/853356/106917517-9f99fb00-6708-11eb-86c3-5c586daac022.png)


> it expands the whole Banner more than in the design

Do you mean the width? But this is expected behaviour:

> A banner always takes the full width of the component it is within.

2021-02-04 16:08 UTC, chaeMil commented on optimus/lib/src/banner.dart
> +          child: Stack(
No i mean height, the close button when used as `OptimusIconButton` is just too big. Or solution would be to have two `Rows` inside each other. The would have ten inner one with, icon, labels and then next to the inner row would be the close button without paddings so it will fill the space correctly.

2021-02-08 10:26 UTC, ookami-kb commented
@chaeMil @Gladkowski I've slightly updated formatting and added docs.

Also, I've removed `Link` from the system-wide banner. It's rather up for a user to set the content, otherwise, it will complicate the layout in case of long text content, etc. Plus, I guess the link would rather be a separate component in the future.

2021-02-08 10:53 UTC, ookami-kb approved these changes

2021-02-08 10:54 UTC, merged