Optimus chat bubbles
MewsSystems/mews-flutter pull request #95
Opened 2021-06-29 10:21 UTC by chaeMil

#### Summary

*Describe anything that you feel other developers should know.*

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-07-01 12:39 UTC, Gladkowski requested changes
- when status is `Sent` no check icon is shown in bubble story
- messages are not centered vertically in bubbles
- in dark mode the text color is black for light blue message bubble, is it supposed to be like that?

2021-07-01 12:39 UTC, Gladkowski commented on storybook/lib/stories/chat/bubble.dart
> +          formatTime: (DateTime input) => '${input.hour}:${input.minute}',
If the time is 14:05 time formats like `14:5`. I suggest using `DateFormat('hh:mm')`.

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +                    : theme.colors.neutral1000t64),
Trailing comma

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +class OptimusChatBubble extends StatelessWidget {
I think that comments should be added to all new classes and fields.

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +                child: tryAgain),
trailing comma

Also `tryAgain` should be wrapped in proper text style or typography component

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +  Widget _messageBubble(OptimusThemeData theme) => Flexible(
Should be renamed to `_buildMessageBubble` since it's not a getter. Applies to all other places

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +  const factory OptimusMessage({
Also I feel like we don't need separate `OptimusMessage` class. All those fields could be part of bubble. But not sure about that

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +enum MessageAlignment {
I would place all enums at the top of the file and add comments

2021-07-01 12:39 UTC, Gladkowski commented on optimus/lib/src/chat/bubble.dart
> +  Padding _status(OptimusThemeData theme) => Padding(
It feels like `_status` can be extracted to separate class/file.

2021-07-01 12:42 UTC, chaeMil commented on storybook/lib/stories/chat/bubble.dart
> +          formatTime: (DateTime input) => '${input.hour}:${input.minute}',
We dont have`intl` library in the optimus library, this is just basic example, you will provide your own function.

2021-07-01 12:46 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +  const factory OptimusMessage({
This way you just provide `List<OptimusMessage>` to the `OptimusChat` widget. No need to creating all the widgets by yourself.

2021-07-01 12:47 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +  Padding _status(OptimusThemeData theme) => Padding(
Why?

2021-07-07 15:15 UTC, chaeMil commented
@Gladkowski ping

2021-07-07 15:27 UTC, Gladkowski approved these changes

2021-07-09 13:11 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +
There shouldn't be new line here.

2021-07-09 13:16 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +  Widget build(BuildContext context) {
`build` should be the last method.

2021-07-09 13:26 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +enum MessageStatus {
Let's rather replace it with something like that:

```dart
@freezed
class MessageState with _$MessageState {
  const factory MessageState.sending({required String text}) =
      MessageStateSending;

  const factory MessageState.sent({required String text}) = MessageStateSent;

  const factory MessageState.error({
    required String text,
    required void Function() onTryAgain,
  }) = MessageStateError;
}
```

2021-07-09 13:27 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +    required this.index,
This widget should know nothing about its index.

2021-07-09 13:28 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +    required this.showDate,
According to our style, it should rather be something like `isDateVisible`, same for other parameters.

2021-07-09 13:31 UTC, ookami-kb commented on storybook/lib/stories/chat/bubble.dart
> +  Option('Organisation avatar', organisationAvatar),
This is confusing, I would remove this option from bubble story at all.

2021-07-09 13:32 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +enum MessageAlignment {
Let's rather extract all the enums and models to a separate file `message.dart`.

2021-07-09 13:36 UTC, ookami-kb requested changes
I've added all the comments separately by accident 🤦

2021-07-09 14:32 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +enum MessageStatus {
Why including the text? Its already in the `OptimusMessage`

2021-07-09 14:45 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +enum MessageStatus {
I mean text of the status here, i.e. "Sending", "Sent", and remove it from the widget constructor.

2021-07-13 12:47 UTC, chaeMil commented
@ookami-kb ping

2021-07-15 09:46 UTC, ookami-kb requested changes

2021-07-15 09:46 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +enum MessageAlignment {
This was not addressed.

2021-07-15 09:46 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +    required void Function() onTryAgain,
`void Function()` can be replaced with `VoidCallback`.

2021-07-15 09:46 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final Function formatDate;
`formatDate` and `formatDate` should have proper type, not just `Function`.

2021-07-15 14:58 UTC, ookami-kb requested changes

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final TryAgainCallback onTryAgainClicked;
`onTryAgainPressed`

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final SendCallback onSendClicked;
`onSendPressed`

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  final List<OptimusMessage> messages;
For lists that a part of public API it's better to do defensive copying. Otherwise, it can be broken by client if the list is changed directly.

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +    required this.onTryAgainClicked,
`onTryAgainPressed`

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +  Widget get _emptyAvatarSpace => const SizedBox(width: 40);
Why is it hard-coded to `40`? What if we will pass avatars of different size? In that case bubbles without avatar would have incorrect padding.

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +          onTap: () {
It's called even if the text is empty. Also, you can reuse `OptimusEnabled` component instead.

2021-07-15 14:58 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +        child: GestureDetector(
There's no visual feedback on button pressed.

2021-07-16 08:17 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +  Widget get _emptyAvatarSpace => const SizedBox(width: 40);
Solved it kinda hacky way, lets see what do you think about it. I couldnt find a way to measure the widget without using `GlobalKey` so its what it is.

2021-07-16 09:07 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +  Widget get _emptyAvatarSpace => const SizedBox(width: 40);
Let's maybe at least move this `SizedBox` up the tree, so that existing avatars are wrapped as well.

2021-07-16 14:45 UTC, ookami-kb requested changes

2021-07-16 14:45 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +          onTap: _isSendEnabled
`OptimusEnabled` takes care of this. No need to explicitly disable tap.

2021-07-16 14:45 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +            scale: _isTappedDown ? 0.7 : 1,
Is it somehow aligned with designers?

2021-07-16 14:45 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +            style: TextStyle.lerp(preset200s,
What's the point of `lerp` here? Why not `copyWith`?

2021-07-16 14:45 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +          fontSize: 12,
Why is here some hard-coded text size? Why is it not aligned with text presets?

2021-07-16 14:48 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +  List<OptimusMessage> get _messages => messages.reversed.toList();
It doesn't make sense to keep the initial parameters and have getter to create a new list every time. Create it during class instantiation.

2021-07-16 14:56 UTC, chaeMil commented on optimus/lib/src/chat/input.dart
> +            scale: _isTappedDown ? 0.7 : 1,
Ehm, nope...

2021-07-16 15:07 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +            scale: _isTappedDown ? 0.7 : 1,
It should be.

2021-07-19 07:45 UTC, chaeMil commented on optimus/lib/src/chat/input.dart
> +            scale: _isTappedDown ? 0.7 : 1,
Confirmed, no visual feedback on button, the visual feedback is that message is sent.

2021-07-19 07:47 UTC, chaeMil commented on optimus/lib/src/chat/bubble.dart
> +          fontSize: 12,
Its like in the design 🤷‍♂️ 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/9150597/126122380-19be7048-710d-4b6a-b8ea-011e6031c285.png">

2021-07-19 08:52 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +            scale: _isTappedDown ? 0.7 : 1,
Weird, but ok.

2021-07-19 08:52 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +          fontSize: 12,
Ok, let's leave it like this for now, but please raise this discussion with designers. AFAIK, there should be no hard-coded typography styles.

2021-07-19 08:59 UTC, ookami-kb requested changes

2021-07-19 08:59 UTC, ookami-kb commented on optimus/lib/src/chat/chat.dart
> +              reverse: true,
Why do you first reverse incoming messages and then build reversed list again?

2021-07-19 08:59 UTC, ookami-kb commented on optimus/lib/src/chat/input.dart
> +    _controller.addListener(() => setState(() {}));
Don't add a listener in build method: with every build, a new listener will be created.

2021-07-19 08:59 UTC, ookami-kb commented on optimus/lib/src/chat/bubble.dart
> +            child: Text(message.message),
You can pass `style` directly to `Text`, why wrap it into `DefaultTextStyle`?

2021-07-19 09:07 UTC, chaeMil commented on optimus/lib/src/chat/chat.dart
> +              reverse: true,
The `parameter` in the `ListBuilder` is used to automatically scroll the list to bottom and to begin from bottom. List of messages is reversed so the newly added message is on the bottom and also the logic is the same as they appears on the screen.

2021-07-19 09:28 UTC, ookami-kb approved these changes

2021-07-19 09:29 UTC, merged