fix(optimus) [RND-63908]
MewsSystems/mews-flutter pull request #96
Opened 2021-06-30 10:47 UTC by Gladkowski

#### Summary

- fix radio title color
- fix dialog 'X' button color
- refactor `default` and `secondary` colors 

#### Testing steps

*Info about test cases. If you think the issue is not testable, describe why.*

#### Follow-up issues

*Is there some action/cleanup needed after this PR is merged or deployed (e.g. consolidate some part outside the scope of this PR, etc)? Create issues for it with deadline and note them here and in the PR comments.*

#### Check during review

- Verify against YouTrack issue.
- Is the PR over 300 additions? Consider rejecting it with advice to split it. Is it over 500 additions? It should definitely be rejected.
- Unused code removed.
- Build passing.
- Is it a bug fix? Check that it is covered by a proper test (unit or integration).

2021-06-30 11:49 UTC, chaeMil approved these changes

2021-07-01 08:48 UTC, ookami-kb requested changes

2021-07-01 08:48 UTC, ookami-kb commented on optimus/lib/src/colors/colors.dart
> +  Color get themeSensitiveDefaultTextColor =>
I think we did it wrong initially. Text colors should be theme specific without explicit mentioning, i.e.:

```dart
Color get defaultTextColor => _isLight ? neutral1000 : neutral0;
Color get invertedTextColor => _isLight ? neutral0 : neutral1000;
```

Same for the secondary color. But we need to check all the usages not to break them.

2021-07-01 11:53 UTC, ookami-kb approved these changes

2021-07-01 11:53 UTC, merged